CONTRIBUTING.md, README.md, docs/admin/tutorial.md, docs/developer/go.md, docs/developer/index.md, docs/index.md, mkdocs.yml
This closes #25 by adding a `CONTRIBUTING.md`, `Admin Guide`, and `Developer Guide`
=> Add useful docs

Cargo.lock, Cargo.toml, xtask/src/build_ebpf.rs, xtask/src/run.rs
Fixes CI and updates Aya dependency to main since the patches carried in my branch are all merged.
=> Fix CI and dependencies

.gitignore, README.md
=> Added docs for dev environment setup and running

.github/workflows/license.yml, .licenserc.yaml
=> Update License Check Workflow

bpfd/src/server/bpf.rs
If you pass a bad section name when loading a program, an error is returned,
but the program metadata is never cleaned up, so subsequent calls fail.
Validate the section name before inserting to the list of extension programs.
Resolves: 31
=> Section name validation

bpfd/src/server/bpf.rs
=> Fix leaking of map fds

README.md, bpfd/src/main.rs, xtask/src/build_ebpf.rs
=> xtask: Always build ebpf in release profile

Cargo.lock, bpfctl/Cargo.toml, bpfd/Cargo.toml
=> deps: Bump prost and tonic

Cargo.lock, README.md, bpfd/Cargo.toml, bpfd/src/main.rs, docs/admin/tutorial.md
If bpfd is running as a service, log to journald.
Resolves: #89
=> Logging to systemd journal

packaging/container-deployment/Containerfile.bpfd-local
remove an incorrectly added Containerfile
=> Added this by accident

.github/workflows/image-build.yaml, Cargo.lock, Cargo.toml, bpfd-agent/Cargo.toml, bpfd-agent/src/bpfd_agent.rs, bpfd-agent/src/crdgen.rs, bpfd-agent/src/finalizer.rs, bpfd-agent/src/main.rs, bpfd-k8s-api/Cargo.toml, bpfd-k8s-api/src/ebpfprogram.v1alpha1.rs, bpfd-k8s-api/src/lib.rs, docs/admin/k8s-deployment.md, packaging/container-deployment/Containerfile.bpfdagent, packaging/kubernetes-deployment/bpfd-core/bpfd-agent-rbac.yaml, packaging/kubernetes-deployment/bpfd-core/bpfd-cert-issuer.yaml, packaging/kubernetes-deployment/bpfd-core/bpfd-certs.yaml, packaging/kubernetes-deployment/bpfd-core/bpfd-config.yaml, packaging/kubernetes-deployment/bpfd-core/bpfd-ds.yaml, packaging/kubernetes-deployment/sample-ebpfprograms/xdp-pass.yaml
fixes #46 
Still some open questions 
- Can we condense API definitions? 
- Do we need another operator to manage the bpfd deployment? 
- should all of this ultimately live here?
=> Deploy on k8s

Cargo.lock, bpfd/src/server/bpf.rs
=> deps: Update Aya

README.md, docs/admin/k8s-deployment.md, docs/admin/tutorial.md
=> Fix several docs issues

README.md
=> Edit to the build directions for first time build

README.md
=> Updated install doc dependencies with libelf-dev

docs/admin/tutorial.md, scripts/install.sh, scripts/setup.sh
=> Updated the installer to start the bpfd service

.github/workflows/installer.yml
=> Adds a workflow to validate bpfd installer/systemd

bpfctl/src/main.rs, bpfd/src/server/rpc.rs
Ensure we don't panic If bpfd fails to process one of the 
commands, Instead report errors to users (both client 
and server side) and continue.
Signed-off-by: Andrew Stoycos <astoycos@redhat.com>
=> Stop some BPFD Panics

bpfd/src/server/bpf.rs
- This aims to resolve #141 and #146
=> Remove the link and dispatcher dir after last program is deleted

.github/workflows/integration-tests.yml
=> Validate bpfctl can connect to the daemon in CI

Cargo.lock, bpfctl/Cargo.toml, bpfctl/src/main.rs, tests/integration-test/src/tests/basic.rs, tests/integration-test/src/tests/utils.rs
Example output /cc @nerdalert 
```
$ sudo ./target/debug/bpfctl list --iface eth0
Type       Position  UUID                                  Name  Priority  Path                                Proceed-On 
xdp (skb)  0         b2475684-13d1-4fe9-a6f6-f3840ade5b15  xdp   100       /var/bpfd/bytecode/xdp_pass_kern.o             
```
=> bpfctl: Add table output for list

tests/integration-test/src/tests/basic.rs
=> Restart bpfd in IT and validate rule persistence

bpfd-agent/src/bpfd_agent.rs
Fix errors flagged by the new nightly clippy.
=> Fix errors flagged by the new nightly clippy.

bpfctl/src/main.rs, bpfd/src/bpf.rs, bpfd/src/multiprog/tc.rs, bpfd/src/multiprog/xdp.rs, docs/admin/configuration.md, docs/admin/tutorial.md, docs/developer/go.md
=> Update docs based on new bpfctl syntax and output

bpfd-ebpf/src/bpf/tc_dispatcher.bpf.c
Remove bpf_printk from tc_dispatcher.bpf.c left over from debugging.
I also reformatted the file with clang-format.
=> Remove bpf printk

.github/workflows/image-build.yaml
Fix bpfd-agent and bpfd-operator
automated image builds.
=> Fix image builds

.github/workflows/image-build.yaml
Finish fixing operator image builds and run the image build action if we change the Action's yaml
=> Trigger image builds on workflow yaml change

README.md
=> Provide package names for Debian/Ubuntu in docs

bpfd-operator/cmd/bpfd-agent/main.go, bpfd-operator/cmd/bpfd-operator/main.go, bpfd-operator/go.mod, bpfd-operator/internal/bpfd-client-helpers.go, bpfd-operator/pkg/bpfd-agent/bpfd-agent.go, bpfd-operator/pkg/bpfd-operator/bpfd-operator.go, go.work, go.work.sum
Woops the name for the operator module wasn't
nested correctly fix it here
Signed-off-by: Andrew Stoycos <astoycos@redhat.com>
=> Fix bpfd-operator module

bpfd/src/bpf.rs
Once a program has been inserted into the list (`self.programs.insert(id, p);`), then if any subsequent errors are encountered, the program must be removed (`self.programs.remove(&id)`).
Resolves: #214
=> Cleanup programs when there is an error adding them

bpfd/src/errors.rs, bpfd/src/lib.rs
=> Command error handling option

bpfd/src/bpf.rs, bpfd/src/multiprog/mod.rs, bpfd/src/multiprog/tc.rs, bpfd/src/multiprog/xdp.rs
=> Add bpfd debug logs for OpenShift issue

bpfd-operator/bundle/manifests/bpfd-operator.clusterserviceversion.yaml, bpfd-operator/config/samples/bpfd.io_v1alpha1_go_counter_bpfprogramconfig.yaml, examples/go-tc-counter/container-deployment/Containerfile.go-tc-counter, examples/go-tc-counter/kubernetes-deployment/go-tc-counter-bytecode.yaml, examples/go-tc-counter/kubernetes-deployment/go-tc-counter.yaml, examples/go-tc-counter/main.go, examples/go-xdp-counter/kubernetes-deployment/go-xdp-counter-bytecode.yaml, examples/go-xdp-counter/kubernetes-deployment/go-xdp-counter.yaml, examples/go-xdp-counter/main.go, examples/pkg/bpfd-app-client/client.go, examples/pkg/config-mgmt/configfile.go, examples/pkg/config-mgmt/param.go
=> Update Go TC Counter to work with bpfd-operator

Cargo.lock, Cargo.toml, bpfd/src/rpc.rs
Point to redhat-et's fork of AYA, fix some small logging things.
=> Fixes for demo

bpfd-operator/pkg/bpfd-agent/bpfd-agent.go
PR #298 moved around where the loadRequest message was being built. The issue is that the loadRequest message was being built after some logic to clear out the proceedOn fields (TC and XDP have different defaults and it is difficult to do a proper deepEqual with the value set). So the loadRequest was being built with a cleared out ProceedOn value. Moved the building of the loadRequest to before the logic to clear the fields.
=> Additional proceedOn fix

README.md
Signed-off-by: Andrew Stoycos <astoycos@redhat.com>
=> add Readme badges

Cargo.lock, Cargo.toml, bpfd/src/bpf.rs, bpfd/src/multiprog/tc.rs, tests/integration-test/src/tests/basic.rs
This set of commits fixes Issue #318.
The code depends on some commits that are in upstream Aya, but not in our fork.  So we either need to pull those commits into our fork (https://github.com/redhat-et/aya/pull/3) or move to upstream Aya, and update the main Cargo.toml before it can be merged.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203910656683151
=> Fix tc hack

Cargo.lock, Cargo.toml, bpfd/src/multiprog/tc.rs, bpfd/src/multiprog/xdp.rs
=> Update to aya main

.github/workflows/build.yml
Needed until https://github.com/clap-rs/clap/issues/4733 is fixed.
=> Pin toolchain to nightly-2023-02-26

.github/workflows/build.yml, bpfd-operator/Makefile, bpfd-operator/cmd/bpfd-agent/main.go, bpfd-operator/cmd/bpfd-operator/main.go, bpfd-operator/controllers/bpfd-agent/common.go, bpfd-operator/controllers/bpfd-agent/internal/bpfd-core.go, bpfd-operator/controllers/bpfd-agent/internal/test-utils/fake_bpfd_client.go, bpfd-operator/controllers/bpfd-agent/tc-program.go, bpfd-operator/controllers/bpfd-agent/tc-program_test.go, bpfd-operator/controllers/bpfd-agent/tracepoint-program.go, bpfd-operator/controllers/bpfd-agent/tracepoint-program_test.go, bpfd-operator/controllers/bpfd-agent/xdp-program.go, bpfd-operator/controllers/bpfd-agent/xdp-program_test.go, bpfd-operator/controllers/bpfd-operator/common.go, bpfd-operator/controllers/bpfd-operator/tc-program.go, bpfd-operator/controllers/bpfd-operator/tc-program_test.go, bpfd-operator/controllers/bpfd-operator/tracepoint-program.go, bpfd-operator/controllers/bpfd-operator/tracepoint-program_test.go, bpfd-operator/controllers/bpfd-operator/xdp-program.go, bpfd-operator/controllers/bpfd-operator/xdp-program_test.go, bpfd-operator/internal/constants.go, bpfd-operator/internal/test-utils/helpers.go
=> Add BpfdOperator Unit test scaffolding and basic unit tests

bpfd/src/oci_utils/image_manager.rs
Ensure bytecode Location on disk includes the registry name if there is one.
Fixes #419
=> Ensure Bytecode location includes registry

.github/workflows/build.yml
Try to fix the upload issues by using the v3 action.
=> .github: Use codecov-action@v3

.github/workflows/build.yml, bpfctl/src/main.rs
Factor out functionality to own functions
Fixes #412
=> Bpfctl refactoring

.gitignore, README.md
Better describe what bpfd is and the problems it solves.
Addresses issue #474.
=> Update bpfd README

CODEOWNERS, CODE_OF_CONDUCT.md, CONTRIBUTING.md, GOVERNANCE.md, MAINTAINERS.md, MEETINGS.md, REVIEWING.md
- Adds the Contributor Covenenat as our CoC
- Adds GOVERNANCE.md based on the CNCF template
- Updates CONTRIBUTING.md based on the CNCF template
- Adds MEETINGS.md to describe community meetings
- Adds MAINTAINERS.md to describe maintainers
- Adds REVIEWING.md basedon the CNCF template
=> Add Project Governance

bpfd-operator/controllers/bpfd-agent/internal/cmp.go
Fix a small bug where an AND should have been an OR :/
This broke the agent's ability to apply updates properly.
=> Fix small bug in statematch

bpfctl/src/main.rs, docs/bpfctl-guide.md, docs/logging.md, docs/tutorial.md
With all the API changes, update the documentation around the tutorial.
=> Update documention for tutorial

tests/integration-test/bpf/tc_pass.bpf.c, tests/integration-test/bpf/tp_openat.bpf.c, tests/integration-test/bpf/xdp_pass.bpf.c, tests/integration-test/src/tests/utils.rs, xtask/src/build_ebpf.rs
Also includes eBPF source files for programs used for integration tests.
=> Add setting of global variables and proceed-on to integration tests

.github/workflows/image-build.yaml
Make sure we build and push the new dispatcher image AFTER we login quay.io/bpfd-bytecode.
=> Fixup actions image build and push.

.github/workflows/image-build.yaml
make sure we're naming the dispatcher images correctly.
=> one last image push fixup

Cargo.lock, bpfctl/Cargo.toml, bpfd-api/Cargo.toml, bpfd-operator/Makefile, bpfd-operator/bundle/manifests/bpfd-operator.clusterserviceversion.yaml, bpfd/Cargo.toml, bpfd/src/multiprog/xdp.rs, changelogs/CHANGELOG-v0.2.1.md
=> Cut release V0.2.1

bpfd/src/bpf.rs
Consolidate some duplicated code in the add_single_attach_program() function.
=> consolidate add_single_attach_program()

.github/workflows/build.yml, .github/workflows/image-build.yaml
As advised here -> https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners
=> fix for ubuntu mirror issues

bpfctl/src/main.rs, docs/developer-guide/logging.md, docs/getting-started/bpfctl-guide.md, docs/getting-started/example-bpf-local.md, docs/getting-started/tutorial.md
Update the docs to incorporate the changes for `bpfctl list --all`, `bpfctl get` and `map-prog-uuid`.
=> Doc updates for bpfctl list --all and map-prog-uuid

bpfd-operator/config/samples/bpfd.io_v1alpha1_tc_pass_tcprogram.yaml
Partially fixes https://github.com/bpfd-dev/bpfd/issues/635
=> Update sample tc program yaml

bpfd/src/bpf.rs, bpfd/src/command.rs, bpfd/src/errors.rs, bpfd/src/multiprog/tc.rs, bpfd/src/multiprog/xdp.rs, bpfd/src/oci_utils/image_manager.rs, bpfd/src/static_program.rs
=> Implement path() as Location method

bpfd-operator/config/samples/bpfd.io_v1alpha1_go_counter_xdpprogram.yaml, bpfd-operator/config/samples/bpfd.io_v1alpha1_tracepoint_tracepointprogram.yaml, bpfd-operator/config/samples/bpfd.io_v1alpha1_xdp_pass_private_xdpprogram.yaml
=> Update remaining sample bpf program yaml files

bpfd-operator/config/samples/bpfd.io_v1alpha1_kprobe_kprobeprogram.yaml, bpfd-operator/config/samples/bpfd.io_v1alpha1_tc_pass_tcprogram.yaml, bpfd-operator/config/samples/bpfd.io_v1alpha1_tracepoint_tracepointprogram.yaml, bpfd-operator/config/samples/bpfd.io_v1alpha1_xdp_pass_xdpprogram.yaml
Note: This was just done for the sample programs that have global variables defined.
=> Add setting of global data to sample yaml files

bpfd/src/command.rs
=> Fix bpfctl load-from-file

docs/developer-guide/testing.md, tests/integration-test/src/main.rs, tests/integration-test/src/tests/basic.rs, tests/integration-test/src/tests/e2e.rs, tests/integration-test/src/tests/mod.rs, tests/integration-test/src/tests/utils.rs, xtask/src/integration_test.rs
Also 
- Moved some repeated code into functions
- Support executing a subset of the integration test cases
Fixes #666 
Fixes #679
=> Add integration tests for load-from-file (and other enhancements)

.vscode/settings.json, Cargo.lock, Cargo.toml, bpfctl/src/main.rs, bpfd/Cargo.toml, bpfd/src/bpf.rs, bpfd/src/command.rs, bpfd/src/errors.rs, bpfd/src/multiprog/mod.rs, bpfd/src/multiprog/tc.rs, bpfd/src/multiprog/xdp.rs, bpfd/src/oci_utils/image_manager.rs, bpfd/src/oci_utils/mod.rs, bpfd/src/serve.rs, bpfd/src/static_program.rs
This commit refactors the ImageManager to be more self contained.
=> bpfd: Move image manager into dedicated thread

bpfctl/src/main.rs
=> Bpfctl use comfy table for all commands

bpfctl/Cargo.toml, bpfctl/src/main.rs
Add std to the hex features.
Remove a clippy nit that shows locally for me.
=> bpfctl: Fix image build

bpfctl/src/main.rs, bpfd/src/bpf.rs
Fixup missed review comments on #701 
-fix bug in updating maps used by
-bpfctl documentation fixes
=> fixup map sharing from review

Cargo.lock, Cargo.toml, bpfd/Cargo.toml, bpfd/src/main.rs, bpfd/src/serve.rs, bpfd/src/storage.rs
Builds on #707 and adds a skeleton CSI plugin where we plan to implement the Controller/Node gRPC APIs on each Host.
=> Add CSI Plugin Skeleton

bpfd-operator/controllers/bpfd-agent/internal/cmp.go, bpfd-operator/controllers/bpfd-operator/kprobe-program_test.go, bpfd-operator/controllers/bpfd-operator/tracepoint-program_test.go, bpfd-operator/controllers/bpfd-operator/uprobe-program_test.go, bpfd-operator/controllers/bpfd-operator/xdp-program_test.go
Address a few minor comments from @astoycos on pr #705
=> Address a few minor comments from astoycos on pr #705

.github/workflows/build.yml
=> ci: adds go mod check

Cargo.lock, Cargo.toml, bpfctl/src/main.rs
Bump these deps all together since they have build dependencies on eachother.
=> bpfd: bump prost,prost-types and tonic

Cargo.lock, bpfd/src/main.rs, bpfd/src/storage.rs, bpfd/src/utils.rs
Pulls in https://github.com/bpfd-dev/aya/commit/27df828e2f95799ecf1f977a003477bbb1b2c011
=> bpfd: Add bpffs helpers to StorageManager

Cargo.lock, Cargo.toml, bpfd-api/src/config.rs, bpfd/Cargo.toml, bpfd/src/oci_utils/cosign.rs, bpfd/src/oci_utils/image_manager.rs, bpfd/src/oci_utils/mod.rs, bpfd/src/serve.rs
This currently verifies that either a signature exist, or does not, based on the config. Additional verficiation schemes can be added later.
=> bpfd: Initial cosign integration

bpfd/src/bpf.rs
bpfd panics with 'map_pin_path must be set after load' when program fails to load
```
$ bpfctl load-from-file --path /run/bpfd/examples/xdp_pass_kern.o --name "pass" xdp --iface vethff657c7 --priority 35
Error = status: Aborted, message: "channel closed", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 29 Sep 2023 02:40:23 GMT", "content-length": "0"} }
Error: Failed to execute request
```
Logs:
```
Sep 28 22:40:22 ebpf03 bpfd[694889]: Map vethff657c7 to 14
Sep 28 22:40:23 ebpf03 bpfd[694889]: thread 'main' panicked at 'map_pin_path must be set after load', bpfd/src/bpf.rs:305:14
Sep 28 22:40:23 ebpf03 bpfd[694889]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Sep 28 22:40:23 ebpf03 bpfd[694889]: RPC load …
```
=> bpfd panic when ebpf program fails to load

docs/developer-guide/debugging.md, mkdocs.yml
Add information on how to debug bpfd with vscode.
=> add debugging documentation

.github/workflows/image-build.yaml
Cleanup out tag setup in ci, remove explicit priorities and add a sha tag.
=> ci: add sha tags to all images

Cargo.lock, bpfd/Cargo.toml, bpfd/src/multiprog/tc.rs
=> bpf: returns an error when adding a tc program to existence clsact qdisc

bpfd/src/bpf.rs, bpfd/src/multiprog/tc.rs, bpfd/src/multiprog/xdp.rs, bpfd/src/utils.rs
Bpfd should skip pinning .data section maps.
=> Don't try and pin .data maps

.github/workflows/build.yml, .licenserc.yaml, README.md, bpf/tc_dispatcher.bpf.c, bpf/xdp_dispatcher_v1.bpf.c, bpf/xdp_dispatcher_v2.bpf.c, examples/go-tc-counter/bpf/tc_counter.c, examples/go-tracepoint-counter/bpf/tracepoint_counter.c, examples/go-xdp-counter/bpf/xdp_counter.c, tests/integration-test/bpf/kprobe.bpf.c, tests/integration-test/bpf/tc_pass.bpf.c, tests/integration-test/bpf/tp_openat.bpf.c, tests/integration-test/bpf/uprobe.bpf.c, tests/integration-test/bpf/xdp_pass.bpf.c
- Update README description of BPF licensing
- Correct SPDX headers for XDP dispatchers
- Correct/Add SPDX headers for bpfd's own bpf code
- clang-formats C files, this should be a lint in CI
=> Fix BPF Licensing

bpfd/src/oci_utils/image_manager.rs, docs/getting-started/bpfctl-guide.md, examples/go-tc-counter/bpf/tc_counter.c, examples/go-tracepoint-counter/bpf/tracepoint_counter.c, examples/go-xdp-counter/bpf/xdp_counter.c, tests/integration-test/src/tests/basic.rs, tests/integration-test/src/tests/utils.rs
See commit messages for details.
=> Fix some panics + add testing and fix for map sharing 

docs/design/daemonless.md
=> docs/design: Add daemonless design doc

docs/blog/posts/bpfd-becomes-bpfman.md
Some small fixups for the "announcing bpfman" blog.
=> blog: some small fixups

.packit.yml, Cargo.lock, Cargo.toml, bpf-metrics-exporter/Cargo.toml, bpfman-api/Cargo.toml, bpfman-ns/Cargo.toml, bpfman.spec, bpfman/Cargo.toml, csi/Cargo.toml, release.toml
- Add packit.yml
- Update specfile to work with packit
- Use pre-release versions in Cargo.toml
=> Packaging and Release Fixes

.packit.sh, README.md, bpfman.spec
- Quick specfile fix to match the syntax of the install commands
- Update README to make the badge syntax easier to maintain + add COPR badge
- Let packit set the RPM version
=> Packaging tweaks

.github/workflows/build.yml
=> bpfman-actions: update -artifact

Cargo.lock, Cargo.toml, xtask/Cargo.toml, xtask/src/build_completion.rs, xtask/src/build_manpage.rs, xtask/src/main.rs
support building manpage and completion scripts for bpfman in xtask
Fixes: #703
=> xtask: add man and completion script generation

bpfman-api/src/config.rs, bpfman-api/src/lib.rs, bpfman/src/bpf.rs, bpfman/src/command.rs, bpfman/src/multiprog/mod.rs, bpfman/src/multiprog/xdp.rs, bpfman/src/utils.rs
Continues to work towards #860
=> Sled fixes, convert xdpdispatcher to use sled, fix loaded_programs race

.github/workflows/build.yml, bpfman-operator/Makefile, bpfman-operator/test/integration/xdp_test.go, go.mod
Remove exposed (undangerous) credentials and internalize them in actions.
=> fixup xdp_pass_private test

bpfman-api/src/config.rs, bpfman/src/bpf.rs, bpfman/src/command.rs, bpfman/src/multiprog/mod.rs, bpfman/src/multiprog/tc.rs, bpfman/src/utils.rs
Finishes https://github.com/bpfman/bpfman/issues/860 depends on the changes in #901  (I'll leave as a draft until that work merges)
=> Sled tc dispatcher

.github/workflows/build.yml, .golangci.yaml, bpfman-operator/controllers/bpfman-agent/common.go, bpfman-operator/controllers/bpfman-agent/uprobe-program.go
=> Enable loggercheck lint

CONTRIBUTING.md, docs/developer-guide/develop-operator.md, docs/developer-guide/testing.md
- Added step to build the example images.
- Moved instructions to testing doc.
=> docs: Update Kubernetes integration test instructions

bpfman-api/src/bpfman.v1.rs, bpfman-api/src/lib.rs, bpfman/src/bpf.rs, bpfman/src/cli/args.rs, bpfman/src/cli/load.rs, bpfman/src/cli/table.rs, bpfman/src/command.rs, bpfman/src/errors.rs, bpfman/src/rpc.rs, tests/integration-test/bpf/build_push_images.sh, tests/integration-test/bpf/fentry.bpf.c, tests/integration-test/src/tests/basic.rs, tests/integration-test/src/tests/utils.rs
Add support for the fentry and fexit program types.
Resolves: #1012
=> bpfman: Add support for fentry/fexit program types

docs/blog/.authors.yml, docs/blog/posts/af_xdp-dp-integration.md
Latest blog broke the docs builds because author wasn't in authors file.
=> docs: Update authors

.github/workflows/build.yml, docs/developer-guide/documentation.md, requirements.txt
This will ensure we don't merge website PRs which
break our documentation deployment.
=> build docs on pull requests

bpfman-operator/test/integration/kprobe_test.go, bpfman-operator/test/integration/uprobe_test.go, examples/config/base/go-target/kustomization.yaml, examples/config/default/go-target/kustomization.yaml
Add kubernetes integration tests for uprobes and kprobes.
Fixes: #636
=> Add kprobe and uprobe k8s integration tests

.packit.yml
Start building for stable on PRs so that we
have some coverage.
Propose downsream RPM releases whenever we cut
a release upstream
=> update packit config

.github/workflows/build.yml, .packit.sh, .packit.yml, Cargo.lock, Cargo.toml, changelogs/CHANGELOG-v0.4.1-rc3.md
- Stop publishing the bpfman-csi crate in actions Since the versioning doesn't changes
- Keep tweaking our packit config to get it working properly for releases.
- Add changelog
=> cut an rc3 release

.github/workflows/build.yml, Cargo.lock, Cargo.toml, changelogs/CHANGELOG-v0.4.1-rc5.md
This adds support for automating the creation of
pre-releases.
=> cut a 0.4.1-rc5

README.md, docs/index.md, docs/quick-start.md
Running through the new "Quick Start" guide, found a few nits that need to be cleaned up.
=> docs: cleanup documentation nits for v0.4.1 release

.github/workflows/image-build.yaml
Make sure we set the push env var when the
image build workflow is run manually.
=> fix push on manual run

examples/Makefile, examples/build-release-yamls.sh
Add `make build-release-yamls` target to generate examples yaml files for a specific release
=> add build releases yaml target for bpfman examples

Cargo.lock, Cargo.toml, changelogs/CHANGELOG-v0.5.0-rc1.md
write changelog, bump necessary versions.
=> cut release 0.5.0-rc1

Cargo.lock, Cargo.toml, RELEASE.md, changelogs/CHANGELOG-v0.5.0.md, examples/config/selinux/go-app-counter/binding.yaml, examples/config/selinux/go-app-counter/kustomization.yaml, examples/config/selinux/go-app-counter/patch.yaml, examples/config/selinux/go-app-counter/patch.yaml.env, examples/config/selinux/go-app-counter/selinux.yaml, examples/config/v0.5.0-selinux/go-app-counter/kustomization.yaml, examples/config/v0.5.0-selinux/go-kprobe-counter/kustomization.yaml, examples/config/v0.5.0-selinux/go-target/kustomization.yaml, examples/config/v0.5.0-selinux/go-tc-counter/kustomization.yaml, examples/config/v0.5.0-selinux/go-tracepoint-counter/kustomization.yaml, examples/config/v0.5.0-selinux/go-uprobe-counter/kustomization.yaml, examples/config/v0.5.0-selinux/go-uretprobe-counter/kustomization.yaml, examples/config/v0.5.0-selinux/go-xdp-counter-sharing-map/kustomization.yaml, examples/config/v0.5.0-selinux/go-xdp-counter/kustomization.yaml, examples/config/v0.5.0/go-app-counter/kustomization.yaml, examples/config/v0.5.0/go-kprobe-counter/kustomization.yaml, examples/config/v0.5.0/go-target/kustomization.yaml, examples/config/v0.5.0/go-tc-counter/kustomization.yaml, examples/config/v0.5.0/go-tracepoint-counter/kustomization.yaml, examples/config/v0.5.0/go-uprobe-counter/kustomization.yaml, examples/config/v0.5.0/go-uretprobe-counter/kustomization.yaml, examples/config/v0.5.0/go-xdp-counter-sharing-map/kustomization.yaml, examples/config/v0.5.0/go-xdp-counter/kustomization.yaml
=> Release v0.5.0

bpfman/src/bin/cli/args.rs, bpfman/src/bin/cli/image.rs, docs/developer-guide/testing.md, examples/Makefile, go.mod, go.sum
Ensure endianness is set correctly.
Ensure selecting bytecode from cilium project
is a bit more graceful/ works with different sub string ordering
=> fixup bytecode image building

bpfman/src/bin/cli/image.rs
For generating build args from a cilium directory, we get the list of bpf object files in the directory and then use the first one in the list to generate the build program and map labels.  However, Aya Object::parse doesn't currently work for S390 files, so if an S390 file happens to be the first one in the list, it doesn't work.
This is a temporary fix that doesn't use S390 files, and if no other type of file exists, it returns an error.
Fixes: #1200
=> Don't use S390 object code for generating build args

Cargo.lock, Cargo.toml
pickup Aya fix for PerfEvent map
=> update Aya to pick fix PR #1004

Cargo.lock, Cargo.toml, bpfman/src/lib.rs, changelogs/CHANGELOG-v0.5.1.md, examples/Makefile, examples/config/v0.5.1-selinux/go-app-counter/kustomization.yaml, examples/config/v0.5.1-selinux/go-kprobe-counter/kustomization.yaml, examples/config/v0.5.1-selinux/go-target/kustomization.yaml, examples/config/v0.5.1-selinux/go-tc-counter/kustomization.yaml, examples/config/v0.5.1-selinux/go-tracepoint-counter/kustomization.yaml, examples/config/v0.5.1-selinux/go-uprobe-counter/kustomization.yaml, examples/config/v0.5.1-selinux/go-uretprobe-counter/kustomization.yaml, examples/config/v0.5.1-selinux/go-xdp-counter-sharing-map/kustomization.yaml, examples/config/v0.5.1-selinux/go-xdp-counter/kustomization.yaml, examples/config/v0.5.1/go-app-counter/kustomization.yaml, examples/config/v0.5.1/go-kprobe-counter/kustomization.yaml, examples/config/v0.5.1/go-target/kustomization.yaml, examples/config/v0.5.1/go-tc-counter/kustomization.yaml, examples/config/v0.5.1/go-tracepoint-counter/kustomization.yaml, examples/config/v0.5.1/go-uprobe-counter/kustomization.yaml, examples/config/v0.5.1/go-uretprobe-counter/kustomization.yaml, examples/config/v0.5.1/go-xdp-counter-sharing-map/kustomization.yaml, examples/config/v0.5.1/go-xdp-counter/kustomization.yaml, xtask/public-api/bpfman.txt
=> Release v0.5.1 for bpfman repo

.tekton/bpfman-pull-request.yaml, .tekton/bpfman-push.yaml, Containerfile.bpfman.openshift
Openshift container to build bpfman and used by konflux pipeline
=> Add bpfman OpenShift container to build bpfman

Containerfile.bpfman.openshift
unblock https://github.com/bpfman/bpfman/pull/1214
=> Fix BUILDPLATFORM redefinition issue in bpfman Containerfile

.tekton/bpfman-push.yaml
=> Add konflux nudging so everytime we have bpfman PR it updates

.github/workflows/build.yml, Cargo.lock, Cargo.toml, xtask/src/public_api.rs
public-api has been fixed, so revert #1256
Resolves: #1260
=>  ci: unpin rust from nightly-2024-09-09

.github/workflows/scorecard.yml, README.md
Adds the OpenSSF Scorecard action to GitHub Actions
=> cI: Create scorecard.yml

bpfman/src/lib.rs
The filter() function used when loading and unloading multi attach programs was getting both TC and TCX programs because they both have the same ProgramType's.  I modified it to just get TC programs and renamed it to get_multi_attach_programs()
This was causing adding tc programs to fail if there were already tcx progrms installed.
I also removed a few more unwrap()s and handled the errors in the process.
=> Modify filter() to just get TC programs

Cargo.lock, Cargo.toml
To pickup fix to https://github.com/aya-rs/aya/issues/1002
=> update aya and  aya-obj

bpfman/src/config.rs, bpfman/src/lib.rs, bpfman/src/multiprog/mod.rs, bpfman/src/multiprog/tc.rs, bpfman/src/multiprog/xdp.rs, bpfman/src/utils.rs
Requested in upstream issue [1120](https://github.com/bpfman/bpfman/issues/1220)
=>  bpfman: Make TC and XDP dispatcher configurable

docs/developer-guide/configuration.md, scripts/bpfman.toml
Update documentation & example config as requested in https://github.com/bpfman/bpfman/pull/1335#pullrequestreview-2414126147 
* Update [scripts/bpfman.toml](https://github.com/bpfman/bpfman/blob/main/scripts/bpfman.toml) with your new fields. I just put the default values in the file, but it helps the user see how to format the values.
* Update the docs with your new fields [docs/developer-guide/configuration.md](https://github.com/bpfman/bpfman/blob/main/docs/developer-guide/configuration.md)
_Originally posted by @Billy99 in https://github.com/bpfman/bpfman/pull/1335#pullrequestreview-2414126147_
=> Update configuration documentation req. PR#1335

bpfman/src/lib.rs, bpfman/src/utils.rs
The removed directories are not used in the current code.
=> Remove legacy dispatcher directories

README.md
=> chore: Fix README images

Cargo.lock, Cargo.toml, xtask/src/public_api.rs
Update public-api to 0.43.0. Also expose the error returned from public-api call.
=> update public-api to 0.43.0

.pre-commit-config.yaml
=> chore: Remove public-api from precommit

bpfman/src/lib.rs, bpfman/src/types.rs
If processing a `bpfman attach` failed in certain scenarios, the link would be added to the program but not to the DB. Once that happens, the program cannot be unloaded.
Example, load an XDP program and then try to attach to an invalid interface.
Step one is in the attach_program() function, once `prog.add_link()` is called, don't exit the function without calling `prog.remove_link()`.
Step two, when in the Program object and walking through the links to build up a list of link objects, if the link is not in the DB, skip over it because there is nothing we can about it at that point. We don't have enough data to detach.
=> bpfman: invalid link fixes

.pre-commit-config.yaml
@dave-tucker 
https://github.com/bpfman/bpfman/issues/1469
=> Add markdown-lint to pre-commit

README.md
Solves: #1482 
Add OpenSSF Best Practices badge to README
=> docs: add OpenSSF Best Practices badge to README

CONTRIBUTING.md
Solves: #1481
I've added a new "Test Policy" section that:
1. Clearly outlines the expectations for unit tests (for functionality that can be easily unit tested)
2. Clarifies when integration tests are required (for major new functionality, especially public-facing APIs)
3. Provides examples and guidance on test documentation and placement
4. Links to the existing testing documentation for more details
The table of contents was also updated to include the new section. This should provide contributors with clear guidelines on the project's testing expectations.
=> Update contributing guide to enhance structure and add testing policies

README.md
Are there any specific steps we need to outline in `README.md`?
=> chore: add issue reporting section to readme

Cargo.toml
Before submitting a Pull Request, please ensure you've done the following:
- 📖 Read the Bpfman Contributing Guide: https://github.com/bpfman/bpfman/blob/main/CONTRIBUTING.md
- 📖 Read the Bpfman Code of Conduct: https://github.com/bpfman/bpfman/blob/main/CODE_OF_CONDUCT.md
- ✅ Add tests according to our Test Policy: https://github.com/bpfman/bpfman/blob/main/CONTRIBUTING.md#test-policy
- 📝 Use descriptive commit messages: https://cbea.ms/git-commit/
- 📗 Update any related documentation.
This PR adds a few more workspace lints in the `bpfman` repository.
- Closes: #1480 
- Relates To: #1480 
_We strongly encourage you to add a test for your changes._
have not been included_
```sh
cd bpfman/
cargo +nightly clippy --all -- --deny warnings
```
```sh
cargo +nightly fmt --all -- --check
``` …
=> feat: add new workspace lints
