Cargo.lock
bpfd/Cargo.toml
bpfd/src/server/bpf.rs
bpfd/src/server/errors.rs
bpfd/src/server/mod.rs
bpfd/src/server/rpc.rs
scripts/certificates.sh

This adds a very simple ACL model.
If API requestor is the owner or superuser, then allow deletion.
The owner is recorded at creation time and derived from the Subject CN
in the certificate.
Fixes: #36

bpfd: Add Program ACLs

---

bpfd/src/server/bpf.rs

When the last program is removed, the dispatcher is still loaded. In the
dispatcher, `num_progs_enabled` is still one, but without a `ctx`, so `prog0()`
is returning `XDP_DISPATCHER_RETVAL` causing all packets on that interface to
drop.
Resolves: #52

`unload` the last program, dispatcher not unloaded

---

bpfd/src/server/bpf.rs
bpfd/src/server/errors.rs

In any of the `bpfctl` commands, if an invalid interface is provide,
`bpfd` panics. Add a check to make sure the interface exists before
proceeding.
Resolves: #63

Prevent panic when invalid interface provided

---

.github/workflows/build.yml

There seems to be some conflict between having both stable and nightly installed. Not sure if it's related to the actions in use or an image change. This patches the problem by only using nightly rust.

ci: Only use nightly

---

packaging/vm-deployment/Vagrantfile
packaging/vm-deployment/bpfd.service
packaging/vm-deployment/provision.yaml

- the Vagrantfile deploys a rawhide VM with virtualbox
for cross-platform support
- the Vagrantfile file calls runs provision.yaml ansible file
- the systemd unit file gets copied to the VM and deployed

Added automated VM build

---

README.md
bpfd/src/main.rs
bpfd/src/server/mod.rs
bpfd/src/server/static_program.rs
docs/admin/configuration.md

fixes #30 
Add the ability to automatically load programs at startup 
Define your programs in `/etc/bpfd/programs.d` like so: 
```toml
[[programs]]
name = "program1"
interface = "docker0"
path = "/home/astoycos/pass.bpf.o"
section_name = "pass"
program_type = "xdp"
priority = 50
[[program]]
name = "program2"
interface = "docker0"
path = "/home/astoycos/pass.bpf.o"
section_name = "pass"
program_type = "xdp"
priority = 55
```
Bpfd will report the load programs and their UUIDs at startup 
```
sudo ./target/debug/bpfd
18:03:27 [WARN] bpfd::server::config: [bpfd/src/server/config.rs:73] No config file provided. Using default
18:03:27 [INFO] bpfd::server::bpf: [bpfd/src/server/bpf.rs:355] Map docker0 to 6
18:03:27 [INFO] bpfd::server: [bpfd/src/server/mod.rs:53] Listening on [::1]:50051 …
```

Add the ability to load programs at daemon startup 

---

bpfd/src/server/static_program.rs

Add code to handle the fact that a file or directory may not be there.
Resolved: #74

bpfd won't run if "/etc/bpfd/programs.d" doesn't exist

---

Cargo.lock
README.md
bpfctl/Cargo.toml
bpfctl/src/main.rs
bpfd/Cargo.toml
bpfd/src/main.rs
docs/admin/tutorial.md

Following Aya, switch bpfd to use env_logger in place of simplelog. By
default, logs are printed at `error` level instead `info`. This can be
overwritten using the `RUST_LOG` environment variable.
`sudo RUST_LOG=info ./target/debug/bpfd`
Resolves: #88

Switch to using env_logger

---

README.md

The commands are explicitly provided for installing the needed dependencies for all cases except for the go protobuf compiler extensions.  It is easy to miss the fact that in this case, you have to go to the link for the instructions instead of just using the commands provided.  This is a small edit to make that more clear.

Make protobuf compiler extensions installation instructions more clear

---

docs/admin/configuration.md
docs/admin/tutorial.md
scripts/certificates.sh
scripts/install.sh
scripts/setup.sh
scripts/user.sh

This is a continuation from #110. Cleanup the initialization scripts
by using variables for USER, USER_GROUP and BINARY. Move
`/etc/bpfd/bytecode/` to `/var/bpfd/bytecode/`.

Change user `bpfctl` to `bpfd-clients`

---

bpfd/src/server/bpf.rs

When rebuilding the state of the previously loaded programs, the `current_position` was not being set. This is the slot in the dispatcher and is only set when the list of programs are sorted.
Resolves: #144

Programs not retrievable with bpfctl list between bpfd restarts

---

Cargo.lock
tests/integration-test/Cargo.toml
tests/integration-test/src/main.rs
tests/integration-test/src/tests/basic.rs
tests/integration-test/src/tests/mod.rs
tests/integration-test/src/tests/utils.rs

- IT tests adds programs, verifies they were installed and then deletes them.
- Added a utils module for routine tasks and broke out the bpfd process spawn from the main module.

Integration tests and spawning bpfd process for IT

---

scripts/certificates.sh

The CI workflow is being blocked because bpfctl can't send to bpfd. This works locally on Fedora and Ubuntu, but fails in CI (also Ubuntu). Looks like the certificates we not being generated properly in CI.
In CI, **bpfctl** logs:
```
Run sudo RUST_LOG=debug ./target/debug/bpfctl --help
[2022-09-27T01:00:14Z DEBUG rustls::anchors] add_parsable_certificates processed 1 valid and 0 invalid certs
[2022-09-27T01:00:14Z DEBUG hyper::client::connect::http] connecting to [::1]:50051
[2022-09-27T01:00:14Z DEBUG hyper::client::connect::http] connected to [::1]:50051
[2022-09-27T01:00:14Z DEBUG rustls::client::hs] No cached session for DnsName(DnsName(DnsName("localhost")))
[2022-09-27T01:00:14Z DEBUG rustls::client::hs] Not resuming any session
[2022-09-27T01:00:14Z DEBUG rustls::client::hs] Using …
```

Fix certs for CI job

---

bpfd/src/server/pull_bytecode.rs
docs/admin/shipping-bytecode.md

Allow bpfd to support pulling bytecode from
the `"application/vnd.docker.image.rootfs.diff.tar.gzip"` Media layer type since it's listed as fully
compliant in the OCI spec.
fixes #184 
Shown working below
```
skopeo inspect --raw docker://docker.io/astoycos/xdp_pass:latest
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"config": {
"mediaType": "application/vnd.docker.container.image.v1+json",
"size": 2990,
"digest": "sha256:c58a3e156ac343086dded8a26d019cdc2557a5e0de52ecaa3f843e96bc76c4cf"
},
"layers": [
{
"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
"size": 1495,
"digest": "sha256:0fa4dca32281cf37f8412ca7b41125fe04a1912360ef7e220dc823f75a2d186c"
}
]
}
```
bpfctl
```
[astoycos@localhost bpfd]$ sudo ./target/debug/bpfctl load …
```

Support Docker gzip layer

---

bpfd-common/src/lib.rs
bpfd-ebpf/src/bpf/tc_dispatcher.bpf.c
bpfd/src/main.rs
bpfd/src/server/bpf.rs
bpfd/src/server/errors.rs
bpfd/src/server/mod.rs
bpfd/src/server/rpc.rs

- Both TC Ingress and Egress are supported.
- The list output is currently hacky because the message format currently only supports XDP programs.  This will be fixed with pr #174. In the meantime, this pr adds the TC programs to the end of the XDP list so they can still be displayed.
- Persistence is not supported.  TC programs will remain loaded and attached if bpfd is terminated without explicitly unloading the TC programs.  If this happens, the TC programs can be cleaned up manually by deleting the associated files in the /var/run/bpfd directory. For example, `sudo rm -rf /var/run/bpfd 2>/dev/null` will clean up all programs loaded by bpfd.

Support tc programs Using the dispatcher approach

---

docs/admin/k8s-deployment.md

`bpfd-agent-rbac.yaml` exists but `bpfd-rbac.yaml` does not exist in https://github.com/redhat-et/bpfd/tree/main/packaging/kubernetes-deployment/bpfd-core
This patch fixes it.

Fix path for the bpfd-agent-rbac.yaml

---

Cargo.lock
bpfd-agent/Cargo.toml
bpfd-agent/src/bpfd_agent.rs
bpfd-k8s-api/Cargo.toml

This patch just includes #194 and #162.
It needs some tweak for the update such as:
- Add `features = ["v1_23"]` to `bpfd-agent/Cargo.toml`
- Tweak `error_policy` argument

Bump k8s-openapi and kube

---

Cargo.lock
bpfctl/Cargo.toml
bpfctl/src/main.rs
bpfd-agent/Cargo.toml
bpfd/Cargo.toml
xtask/Cargo.toml

This patch just includes #202.
It needs to update the following annotations as per [clap's CHANGELOG.md](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md).
* `parse(from_os_str)` to `value_parser`
> For #[clap(parse(from_os_str)] for PathBuf, replace it with #[clap(value_parser)] (as mentioned earlier this will call value_parser!(PathBuf) which will auto-select the right ValueParser automatically).
* `multiple = true` to `num_args(0..)`
> Replace Arg::multiple_values(true) with Arg::num_args(1..)
* Value in `conflicts_with_all` and `required_unless_present` to case sensitive.
> (derive) Leave Arg::id as verbatim casing, requiring updating of string references to other args like in conflicts_with or requires (#3282)

Update clap to v4 

---

bpfctl/src/main.rs

This patch changes to parse option before checking cert files.
Otherwise, the command always fail even `--help` without cert files setup.
Fix https://github.com/redhat-et/bpfd/issues/210

Parse option before checking cert files

---

bpfd/src/bpf.rs

Rebuiding state for TC programs isn't fully supported yet. The current code loads the programs and adds them to the programs list, but doesn't rebuild the TC dispatchers.  As a result, list programs crashes bpfd if there were any TC programs saved.

Skip rebuilding state for TC programs.

---

bpfd/src/multiprog/tc.rs

This got broken in pr #174.  
`const TC_ACT_PIPE` used to be used as a mask, but the code was changed so that it was being used as a shift value.

Fix proceedon for tc

---

bpfd/src/bpf.rs
bpfd/src/multiprog/mod.rs
bpfd/src/multiprog/tc.rs
bpfd/src/multiprog/xdp.rs
tests/integration-test/src/tests/basic.rs

Rebuild TC dispatcher state.
Fixes https://github.com/redhat-et/bpfd/issues/235
A couple of key points to note:
- I reduced the number of priority levels used by TC to two. That's all we really need -- one for the current dispatcher and a second one for the new dispatcher.
- I reload the TC dispatcher 3 times when rebuilding state so that it clears out the old dispatcher.
Both of these workarounds can be removed when https://github.com/aya-rs/aya/pull/445 lands upstream.
TODO:

Rebuild TC dispatcher state

---

bpfd-operator/README.md
bpfd-operator/bundle/manifests/bpfd-operator.clusterserviceversion.yaml
bpfd-operator/config/samples/bpfd.io_v1alpha1_go_counter_bpfprogramconfig.yaml
bpfd-operator/config/samples/bpfd.io_v1alpha1_tc_pass_bpfprogramconfig.yaml
bpfd-operator/config/samples/bpfd.io_v1alpha1_tracepoint_bpfprogramconfig.yaml
bpfd-operator/config/samples/bpfd.io_v1alpha1_xdp_pass_bpfprogramconfig.yaml
bpfd/src/static_program.rs
docs/admin/tutorial.md
docs/developer/go.md
examples/go-tc-counter/kubernetes-deployment/go-tc-counter-bytecode.yaml
examples/go-xdp-counter/kubernetes-deployment/go-xdp-counter-bytecode.yaml
examples/pkg/config-mgmt/param.go
tests/integration-test/src/tests/utils.rs

This commit renames all of the existing
bytecode container images from `quay.io/bpfd/bytecode:<PROG>` to `quay.io/bpfd-bytecode/<PROG>:latest`
Signed-off-by: Andrew Stoycos <astoycos@redhat.com>

Bulk rename of bytecode images

---

.github/workflows/build.yml

Known upstream issue. Pin to nightly-2023-01-10 until resolved.
```
$ cd bpfd-ebpf/
$ cargo +nightly clippy --all -- --deny warnings
Downloaded compiler_builtins v0.1.85
Downloaded 1 crate (167.5 KB) in 0.20s
Compiling compiler_builtins v0.1.85
Compiling core v0.0.0 (/home/bmcfall/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
Compiling proc-macro2 v1.0.36
Compiling unicode-xid v0.2.2
Compiling syn v1.0.86
Compiling aya-bpf-cty v0.2.1 (https://github.com/aya-rs/aya?branch=main#2a182393)
Compiling aya-bpf-bindings v0.1.0 (https://github.com/aya-rs/aya?branch=main#2a182393)
Compiling aya-bpf v0.1.0 (https://github.com/aya-rs/aya?branch=main#2a182393)
Compiling quote v1.0.15
error: cannot find macro `atomic_int` in this scope
--> …
```

Temporarily pin to nightly-2023-01-10

---

packaging/container-deployment/Containerfile.bpfctl
packaging/container-deployment/Containerfile.bpfctl.local
packaging/container-deployment/Containerfile.bpfd
packaging/container-deployment/Containerfile.bpfd.local

Changes 1.63.0-bullseye tag to 1-slim, which is currently Rust 1.66 on Bullseye. This fixes the image build error introduced in the latest dependency bump and hopefully reduces likelihood of it happening again while also reducing image size by moving to a slim variant

containers: Use latest stable rust

---

packaging/container-deployment/Containerfile.bpfctl
packaging/container-deployment/Containerfile.bpfctl.local
packaging/container-deployment/Containerfile.bpfd
packaging/container-deployment/Containerfile.bpfd.local

We currently have an error in [Build and Push Images](https://github.com/redhat-et/bpfd/actions/runs/3941440676/jobs/6743848472).
@dave-tucker suggested that using the non-slim variant of Rust may fix it.

Attempt to fix error in Build and Push Images

---

bpfctl/src/main.rs
bpfd-operator/internal/bpfd-client-helpers.go
bpfd-operator/pkg/bpfd-agent/bpfd-agent.go

The proceed-on field in the bpfprogramconfig is not being sent from bpfd-agent to bpfd.

Propogate proceed-on from bpfd-agent to bpfd

---

bpfd-operator/Makefile
bpfd-operator/internal/bpfd-client-helpers.go

This patch changes from using the `arch` command to `go env GOARCH` to make the build more portable.
Also ran `gofmt` on some files that needed it.
Also removes a `test` call which @astoycos and I discussed as needing to change.

fix: use GOARCH in mk for cm_verify

---

bpfd-operator/hack/bpfprogramconfigs.sh
bpfd-operator/hack/bpfprograms.sh
docs/k8s-deployment.md

The BpfProgramConfig script uses `kubectl` with `-o custom-columns` and the BpfProgram script uses `kubectl` with `-o jsonpath`.
Step one in Issue #226

Add usability scripts to display k8s objects in a summary format

---

.github/workflows/build.yml

Issue with upstream rust toolchain has been resolved. Go back to using nightly instead of pinned version.
Resolves: #279

Unpin from nightly-2023-01-10

---

bpfctl/src/main.rs
bpfd/src/command.rs
bpfd/src/lib.rs
bpfd/src/multiprog/mod.rs
bpfd/src/multiprog/tc.rs

The configuration of `proceed-on` is not supported yet for TC programs, and issue #299 has been opened to track this.  However, the default configuration was working. 
This pr reverts two commits that broke the default configuration of `proceed-on` for TC programs.  Additionally, most of the code that was removed will be needed when support is added for Issue #299.
It turns out that the configuration of `proceed-on` was actually mostly working, but it was wrong in that TC would get configured with the XDP return values, and this would result in unexpected behavior.  So, in addition to reverting the two commits, this pr logs a warning message if the user configures `proceed-on` for TC.

Restore default proceed-on behavior for TC

---

.github/workflows/build.yml
bpfd-api/src/bpfd.v1.rs

Fixes issue https://github.com/redhat-et/bpfd/issues/348.
Running `cargo xtask build-proto` also resulted in updates to `bpfd.v1.rs`.  I assume this is due to updates in the rust tools.

Unpin toolchain from nightly-2023-02-26

---

bpfctl/src/main.rs
bpfd-api/src/config.rs
bpfd-operator/cmd/bpfd-agent/main.go
bpfd-operator/internal/bpfd-client-helpers.go
bpfd/src/lib.rs
docs/configuration.md
examples/go-tc-counter/main.go
examples/go-xdp-counter/main.go
examples/pkg/config-mgmt/configfile.go
scripts/bpfd.toml

The listening endpoint being used was hardcoded, which can lead to a number of problems in a production system. With this change, we allow users to configure what the listening address will be.
Fixes: #379

Make listening endpoint configurable

---

Cargo.lock
bpfctl/Cargo.toml
bpfctl/src/main.rs
bpfd-api/src/config.rs
bpfd-api/src/util.rs
bpfd/Cargo.toml
bpfd/src/lib.rs

Allow bpfd to listen on uds. This listener does no TLS checking. The location for the socket is configurable through the grpc.endpoint.unix field in bpfd.toml.
bpfctl now attempts to communicate over the UDS before attempting the tcp socket with TLS.
Fixes #317

Use Unix Domain Sockets

---

Cargo.lock
bpfd/Cargo.toml

Still seeing issues locally even though CI was green
Reverts redhat-et/bpfd#399
reopen #398

Revert "build(deps): bump openssl from 0.10.47 to 0.10.50"

---

bpfd-operator/apis/v1alpha1/bpfprogramconfig_types.go
bpfd-operator/config/crd/bases/bpfd.io_bpfprogramconfigs.yaml

Please refer to the error in https://github.com/redhat-et/bpfd/issues/426
We always need to specify `imagepullpolicy`, even though it has a `default` value. This patch drops `imagepullpolicy` from required list.
Fix https://github.com/redhat-et/bpfd/issues/426

Drop `imagepullpolicy` from required list

---

.github/workflows/put-issue-in-project.yaml

In order to manage our issues from a single pane of glass it makes sense to have a bot simply triage all issues into our bpfd project.

Add Action to put all issues in project

---

bpfd/Cargo.toml
bpfd/src/certs.rs

Connection to bpfd over TLS broken with the bump to openssl 0.10.52.
$ ./go-xdp-counter -iface vethdd340d3
2023/04/28 08:18:24 Using Input: Interface=vethdd340d3 Priority=50 Source=0xc000548670 2023/04/28 08:18:24 Reading /etc/bpfd/gocounter.toml ... 2023/04/28 08:18:24 Read /etc/bpfd/gocounter.toml failed: err open /etc/bpfd/gocounter.toml: no such file or directory 2023/04/28 08:18:24 rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is valid for localhost,IP:127.0.0.1, not localhost"
NOTE: openssl was bumped in the Cargo.lock file, but wasn't bumped in bpfd/Cargo.toml,
so bumped in toml file as well.

With openssl bump to 0.10.52, tls broken

---

bpfd-operator/controllers/bpfd-agent/tc-program.go
bpfd-operator/controllers/bpfd-agent/tracepoint-program.go
bpfd-operator/controllers/bpfd-agent/xdp-program.go
bpfd/src/bpf.rs
bpfd/src/command.rs
bpfd/src/errors.rs
bpfd/src/multiprog/mod.rs
bpfd/src/multiprog/tc.rs
bpfd/src/multiprog/xdp.rs
bpfd/src/rpc.rs

This reverts parts of the 624b991 that changed bpfd's internal ID from UUID to String, which therefore removed UUID validation.
UUIDs coming over gRPC are String, since using a byte-based encoding might not be the easiest thing to use in all potential client languages.
However, once received from gRPC, UUIDs should be stored in UUID format, and any parsing failures should be returned to the caller.

bpfd: Fix UUID Validation

---

bpfctl/src/main.rs

With the addition of Unix Sockets, there was a missing return statement when an error was encountered when trying over socket.
Resolves: #447

bpfctl is retrying failed operations over TCP

---

bpfctl/src/main.rs
bpfd-api/src/lib.rs
bpfd-ebpf/src/bpf/tc_dispatcher.bpf.c
bpfd-operator/controllers/bpfd-agent/tc-program.go
bpfd/src/bpf.rs

Fixes  issue #299.
A key point to understand about this implementation the following:
Valid TC return values range from -1 to 8.  Since -1 is not a valid shift value, 1 is added to the value to determine the bit to set in the bitmask and, correspondingly, The TC dispatcher adds 1 to the return value from the BPF program before it compares it to the configured bit mask.
I also tweaked the display for `bpfctl list` a little.

Finish implementing support for TC proceed-on

---

Cargo.lock
bpfctl/Cargo.toml
bpfd-api/Cargo.toml
bpfd/Cargo.toml
bpfd/src/certs.rs
codecov.yml
scripts/certificates.sh
scripts/setup.sh
xtask/Cargo.toml

The tonic bump to 0.9.2 brought in rustls 0.20.0. With this bump, as well as the bump of OpenSSL to 0.10.52, mTLS between client and server were broken.
There was a bug in rustls (see https://github.com/rustls/rustls/issues/1288) where the certificate created by the rust server could not be parsed by the GO client (but an identical OpenSSL based certificate could be parsed). This was fixed in rustls 0.21.1.
rust-openssl was also updated in this timeframe, which cause an error parsing the rust generated certificate in the rust client (bpfctl). See https://github.com/rustls/rustls/issues/1292. This is fixed by this PR by changing how the certicate was created. The `.dns()` line below was causing the problem. A partial fix was implemented in #448, which fixed the GO clients, but the rust …

Bump tonic to 0.9.2 and rustls to 0.21.1

---

bpfd-api/src/lib.rs
bpfd-operator/apis/v1alpha1/tcProgram_types.go
bpfd-operator/config/crd/bases/bpfd.io_tcprograms.yaml
bpfd-operator/controllers/bpfd-agent/tc-program_test.go
bpfd-operator/controllers/bpfd-operator/tc-program_test.go

This makes our default TC dispatcher behavior the same as standard TC:
`TC_ACT_OK`, will terminate the packet processing pipeline and allows the packet to proceed
`TC_ACT_PIPE`, will iterate to the next action, if available

Remove Ok from TCProceedOn defaults

---

README.md

We need this badge to get the netlify OSS license.

Add Netlify badge to README

---

bpfctl/src/main.rs
bpfd-api/src/config.rs
bpfd-operator/cmd/bpfd-agent/main.go
bpfd-operator/internal/constants.go
bpfd-operator/internal/tls/tls.go
bpfd/src/bpf.rs
bpfd/src/serve.rs
docs/configuration.md
examples/go-tc-counter/main.go
examples/go-xdp-counter/main.go
examples/pkg/config-mgmt/configfile.go
scripts/bpfd.toml

Endpoint configuration now allows multiple unix and TCP sockets to be used for use as both server in bpfd and client in bpfctl. Individual endpoints can also be enabled and disabled via configuration. For client connections, priority is determined by the order the endpoints are listed in the TOML configuration file.
Fixes #418 
TODO:

Improve endpoint configuration

---

bpfd/src/bpf.rs
bpfd/src/multiprog/tc.rs
bpfd/src/multiprog/xdp.rs

With changes in pr #372, the BpfLoader was getting re-initialized after the global values were set.
Fixes: #500

Fix setting of global data in extension programs

---

Cargo.lock
bpfctl/Cargo.toml
bpfd-api/Cargo.toml
bpfd-operator/Makefile
bpfd-operator/bundle/manifests/bpfd-operator.clusterserviceversion.yaml
bpfd-operator/hack/boilerplate.sh.txt
bpfd/Cargo.toml
changelogs/CHANGELOG-v0.2.0.md

This adds the changelog for bpfd's 0.2.0 release.
Updates the bpfd-operator bundle version.
Updates the bpfd, bpfctl, and bpfd-api versions to 0.2.0.
Fixes a small bug in one of our boilerplates
Fixes #393

Cut 0.2.0 release

---

.github/workflows/build.yml

Try to temporally fix our CI by reverting the ubuntu base image.

Temp fix for Ubuntu-latest mirror issue

---

bpfd-operator/apis/v1alpha1/shared_types.go
bpfd-operator/controllers/bpfd-agent/common.go
bpfd-operator/controllers/bpfd-agent/tc-program.go
bpfd-operator/controllers/bpfd-agent/tc-program_test.go
bpfd-operator/controllers/bpfd-agent/tracepoint-program.go
bpfd-operator/controllers/bpfd-agent/tracepoint-program_test.go
bpfd-operator/controllers/bpfd-agent/xdp-program.go
bpfd-operator/controllers/bpfd-agent/xdp-program_test.go
bpfd-operator/controllers/bpfd-operator/common.go
bpfd-operator/controllers/bpfd-operator/configmap.go
bpfd-operator/controllers/bpfd-operator/configmap_test.go
bpfd-operator/controllers/bpfd-operator/tc-program.go
bpfd-operator/controllers/bpfd-operator/tc-program_test.go
bpfd-operator/controllers/bpfd-operator/tracepoint-program.go
bpfd-operator/controllers/bpfd-operator/tracepoint-program_test.go
bpfd-operator/controllers/bpfd-operator/xdp-program.go
bpfd-operator/controllers/bpfd-operator/xdp-program_test.go
bpfd-operator/internal/constants.go
bpfd-operator/pkg/helpers/helpers.go

This moves the cluster and node level condition types into the public API, as a first step for #430.
Partially resolves #430.

chore: move condition types to public API

---

bpfd-operator/Makefile

Replace missed bpfd-deployment with the KIND_CLUSTER_NAME variable

Makefile: fixup cluster name substitution

---

.github/workflows/image-build.yaml
Containerfile.xdp_dispatcher_v1
Containerfile.xdp_dispatcher_v2
bpf/xdp_dispatcher_v1.bpf.c
bpf/xdp_dispatcher_v2.bpf.c
bpfd/src/dispatcher_config.rs
bpfd/src/multiprog/xdp.rs
xtask/src/build_ebpf.rs

This adds a new XDP dispatcher with the adjusted XdpDispatcherConfig struct to work with the v2 of the dispatcher per the libxdp protocol spec.
Note: This doesn't (yet) handle frags support, which is something that will be implemented later on - which was the primary motivation for dispatcher v2.
Updates: #319 
Updates: #533 (Adds dispatcher image push)

bpfd: Use XDP dispatcher v2

---

.github/workflows/build.yml
docs/developer-guide/testing.md
mkdocs.yml
tests/integration-test/bpf/build_push_images.sh
tests/integration-test/src/tests/basic.rs
tests/integration-test/src/tests/e2e.rs
tests/integration-test/src/tests/mod.rs
tests/integration-test/src/tests/utils.rs

The existing integration tests validate the basic loading, unloading, and cli functionality for bpfd.  However, they do not validate that the programs are actually running or that any of the advanced features actually work.  This commit adds support for these functions to include the following.
eBPF Integration Test Framework:
- Create and use a network namespace with a veth pair and IP addresses for testing XDP and TC programs
- Start, capture, and retrieve the output of pings to the network namespace to generate traffic for these programs
- Capture and retrieve `/sys/kernel/debug/tracing/trace_pipe` so that `bpf_printk()` logs from eBPF programs can be examined
The above provides a framework with which functionality can be easily tested by adding and examining `bpf_printk()` output …

Add e2e testing to bpfd integration test

---

.github/workflows/build.yml
bpfd-operator/test/integration/suite_test.go
docs/getting-started/example-bpf-k8s.md
examples/Makefile
examples/config/base/go-tc-counter/deployment.yaml
examples/config/base/go-tracepoint-counter/deployment.yaml
examples/config/base/go-xdp-counter/deployment.yaml

Add targets to the examples makefile to build all the user space images and to easily load them into kind.
Also update our Kubernetes integration tests to use fresh userspace images in CI.

Example build target

---

bpfd-operator/cmd/bpfd-agent/main.go
bpfd-operator/controllers/bpfd-agent/discovered_program.go
bpfd-operator/controllers/bpfd-agent/discovered_program_test.go
bpfd-operator/controllers/bpfd-agent/internal/bpfd-core.go
bpfd-operator/controllers/bpfd-agent/internal/test-utils/fake_bpfd_client.go
bpfd-operator/controllers/bpfd-operator/configmap.go
bpfd-operator/internal/constants.go
bpfd-operator/internal/k8s.go

Works towards finishing #320 
This adds a new controller that creates bpfProgram object for programs not owned by bpfd.
These bpfProgram objects contain annotations which reflect kernel state as shown below
```bash
kubectl get bpfprograms -l bpfd.dev/unownedProgram -l kubernetes.io/hostname=bpfd-deployment-worker
NAME                                           AGE
dump-bpf-map-693-bpfd-deployment-worker        17h
dump-bpf-prog-694-bpfd-deployment-worker       17h
my-uretprobe-93125-bpfd-deployment-worker      17h
restrict-filesy-63130-bpfd-deployment-worker   17h
sd-fw-egress-63149-bpfd-deployment-worker      17h
sd-fw-egress-63171-bpfd-deployment-worker      17h
sd-fw-egress-63173-bpfd-deployment-worker      17h
sd-fw-egress-63175-bpfd-deployment-worker      17h …
```

List programs k8s

---

.github/workflows/image-build.yaml

Now that we no longer track the olm bundle on disk, ensure we generate the bundle manifests before building and pushing the bundle-image in actions.

generate olm bundle before building bundle-image

---

bpfd-operator/controllers/bpfd-agent/internal/cmp.go
bpfd-operator/controllers/bpfd-agent/tc-program.go
bpfd-operator/controllers/bpfd-agent/tracepoint-program.go
bpfd-operator/controllers/bpfd-agent/xdp-program.go

In bpfd-operator, the compare function DoesProgExist() compares the current LoadRequest values to the what is loaded in bpfd in the ListResult. The compare was comparing the pointer values of the Id instead of the actual strings, so it always indicated that there change. This caused the calling function to always unload and reload the EBPF Program.

bpfd-operator: Reduce the number of unload/reloads

---

bpfd/src/bpf.rs
bpfd/src/command.rs
bpfd/src/static_program.rs

The direction field for tc programs was at the wrong level internally fix this by moving the field into tcProgramInfo. Add a comment to `ProgramData`.

move direction to tcInfo

---

bpfd/src/bpf.rs
docs/getting-started/bpfctl-guide.md

There was a check in bpfd which prevent an eBPF program from being deleted if it's maps were being referenced by another eBPF Program. The check was added during the original map sharing PR because it caused problems, but that is no longer the case.
bpfd used to remove the Map Owner from the list of UUIDs in the MapsUsedBy field, because it looked cleaner. The Map Owner is now included in the list of UUIDs in the MapsUsedBy because the Map Owner eBPF Program can now be unloaded, so it is useful to know if it is there or not.

Remove check to block unloading of a Map Owner

---

bpfd-operator/controllers/bpfd-agent/common.go
bpfd-operator/controllers/bpfd-agent/discovered_program_test.go
bpfd-operator/controllers/bpfd-agent/kprobe-program.go
bpfd-operator/controllers/bpfd-agent/kprobe-program_test.go
bpfd-operator/controllers/bpfd-agent/tc-program.go
bpfd-operator/controllers/bpfd-agent/tc-program_test.go
bpfd-operator/controllers/bpfd-agent/tracepoint-program.go
bpfd-operator/controllers/bpfd-agent/tracepoint-program_test.go
bpfd-operator/controllers/bpfd-agent/xdp-program.go
bpfd-operator/controllers/bpfd-agent/xdp-program_test.go
bpfd-operator/controllers/bpfd-operator/common.go
bpfd-operator/hack/kind-config.yaml
bpfd/src/oci_utils/image_manager.rs

fix a race that @Billy99 found where we were creating a bpfProgram even though the parent *Program was being deleted.
In the meantime try and cleanup the core shared code to be a bit easier to understand. 
Functionally the main change here is that now a given BpfProgram will be created and reconciled in the same loop meaning that all bpfProgram objects wont be created before any program is actually loaded via bpfd.

Fix  bpfd-agent race

---

docs/index.md

Though 2 spaces seem to work in a lot of places, and my markdown linter complains about indenting by 4 spaces, mkdocs is apparently looking for 4 spaces to define a sub-bullet.

Fix multi-level indentation issue on home page

---

bpfd-operator/apis/v1alpha1/shared_types.go
bpfd-operator/controllers/bpfd-agent/common.go
bpfd-operator/controllers/bpfd-agent/kprobe-program.go
bpfd-operator/controllers/bpfd-agent/tc-program.go
bpfd-operator/controllers/bpfd-agent/tracepoint-program.go
bpfd-operator/controllers/bpfd-agent/xdp-program.go
bpfd-operator/controllers/bpfd-operator/common.go
bpfd-operator/internal/constants.go
bpfd-operator/pkg/helpers/helpers.go

With the original bug, if there was a problem with GetBytecode(), the bpfProgram object would have been created, but the program would fail to load because GetBytecode() would fail and return.  We didn’t tell the user why it failed and you couldn’t delete the *program object because in order to do that, you need to call reconcileBpfdProgram(), which requires the bytecode interface.
Andrew’s recent pr changed the behavior so that the bpfProgram objects get created only after the GetBytecode() succeeds.  This is better because you don’t have the bpfProgram object that can’t be deleted, but because you don’t have the bpfProgram object, you don’t know why it failed unless you look at the agent logs.
Both versions still had a problem where if the secret gets deleted (or changed so it doesn’t …

Handle and report bytecode selector errors

---

bpfd/src/bpf.rs
bpfd/src/command.rs
bpfd/src/errors.rs
bpfd/src/multiprog/tc.rs
bpfd/src/multiprog/xdp.rs
bpfd/src/oci_utils/image_manager.rs
bpfd/src/rpc.rs
bpfd/src/serve.rs
bpfd/src/static_program.rs

This commit aims to simplify our internal api.  Specifically it removes many redundant types and centers the entire internal API around a Program Enum which contains all of the core information needed to load and maintain a program.
Most of the code deduplication comes out of command.rs and within our listing API. 
All internals of loading and pinning stay the same.
follows up https://github.com/bpfd-dev/bpfd/pull/656

simplify internal API

---

bpfd/src/bpf.rs
bpfd/src/multiprog/mod.rs
bpfd/src/multiprog/tc.rs
bpfd/src/multiprog/xdp.rs

separate dispatchers from programs in BpfManager
Separate dispatchers and programs into their own unique types
since they currently have very different lifetime requirements
in the codebase today.
This includes adding getters/setters and helper traits for each
type.
Ultimately this now enables us to pass around a mutable reference
to a program throughout a program operation (load/delete/reload/etc)
which makes the entire cycle a bit more efficient now that we need
to update a program's kernel info AFTER load.

separate dispatchers from programs in BpfManager

---

Cargo.lock
bpfctl/Cargo.toml
tests/integration-test/src/tests/basic.rs

All the "bpfctl --help" variations are failing:
```
$ bpfctl list --help
error: unexpected argument found
```
Update the bpfctl Cargo.toml file to use the "default" feature flags, which includes: std, color, help, usage, error-content, suggestions
Also add a test to detect this in the future.

"bpfctl --help" fails

---

bpfd-api/src/util.rs
bpfd/src/main.rs
bpfd/src/serve.rs
bpfd/src/storage.rs
bpfd/src/utils.rs

Implement the scaffolding required CSI endpoints for ephemeral inline volumes.
Currently the plugin just prints info on `NodePublishVolume` and `NodeUnPublishVolume`
i.e 
```
[INFO  bpfd::storage] Received publish volume request with :
volume_caps: Some(
VolumeCapability {
access_mode: Some(
AccessMode {
mode: SingleNodeWriter,
},
),
access_type: Some(
Mount(
MountVolume {
fs_type: "",
mount_flags: [],
volume_mount_group: "",
},
),
),
},
),
volume_id: csi-413a3e6b41db24365286e94018a6644fa3190b8ab99b63269519562af55b8930,
target_path: /var/lib/kubelet/pods/fcd164d3-cbe8-4044-8efd-c7f3e46b046d/volumes/kubernetes.io~csi/bpf-maps/mount,
volume_context: {},
read_only: false
```

bpfd/csi: ephemeral inline volume scaffolding

---

bpfd-operator/config/samples/bpfd.io_v1alpha1_tracepoint_tracepointprogram.yaml
bpfd-operator/controllers/bpfd-agent/kprobe-program.go
bpfd-operator/controllers/bpfd-agent/tc-program.go
bpfd-operator/controllers/bpfd-agent/tracepoint-program.go
bpfd-operator/controllers/bpfd-agent/uprobe-program.go
bpfd-operator/controllers/bpfd-agent/xdp-program.go

Fixes #733, "Can't delete programs with errors in k8s"
The problem was that if a program was being deleted, and it wasn't loaded for some reason (most likely due to an error), the code returned BpfProgCondNotLoaded.  While this is true, the problem is that the code treats this condition as an error, so the delete never completes.  The fix is to return BpfProgCondUnloaded, which is what the code is expecting to see when a program is being deleted.
Also fixed a problem with the sample tracepoint yaml.

Allow bpf programs with errors to be deleted in k8s

---

xtask/src/build_ebpf.rs

```
error: the borrowed expression implements the required traits
--> xtask/src/build_ebpf.rs:89:30
|
89 |     let files = fs::read_dir(&src_path).unwrap();
|                              ^^^^^^^^^ help: change this to: `src_path`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrows_for_generic_args
= note: `-D clippy::needless-borrows-for-generic-args` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::needless_borrows_for_generic_args)]`
```

Fix new clippy error

---

bpfctl/src/main.rs

When using a Unix socket, bpfctl calls to bpfd fail:
```
$ bpfctl list
Error = transport error
Caused by:
0: error trying to connect: Connecting to HTTPS without TLS enabled
1: Connecting to HTTPS without TLS enabled
Error: Failed to execute request
```
To use a Unix socket, add/modify the bpfd.toml file and restart bpfd:
```
sudo vi /etc/bpfd/bpfd.toml
[[grpc.endpoints]]
type = "unix"
enabled = true
path = "/run/bpfd/bpfd.sock"
```
The fix is to update the address being passed to bpfd.

bpfctl calls fail when using Unix socket

---

bpfd/src/bpf.rs

bpfd panics on unload with an id that is not of a bpfd program:
```
bpfctl unload 22222
Error = status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
Caused by:
0: transport error
1: connection error: unexpected end of file
2: unexpected end of file
```
```
Oct 02 16:53:54 ebpf03 bpfd[1032526]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', bpfd/src/bpf.rs:618:50
Oct 02 16:53:54 ebpf03 bpfd[1032526]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

bpfd: bpfd panic on unload of id not owned by bpfd

---

.github/workflows/image-build.yaml

Follow-up to #754, the following images were missing:
tc_pass
uretprobe
kretprobe

ci: Add missing ci bytecode images

---

bpfd-operator/controllers/bpfd-agent/common.go
bpfd-operator/controllers/bpfd-agent/kprobe-program.go
bpfd-operator/controllers/bpfd-agent/xdp-program_test.go
bpfd-operator/controllers/bpfd-operator/common.go
bpfd-operator/controllers/bpfd-operator/kprobe-program.go
bpfd-operator/controllers/bpfd-operator/kprobe-program_test.go
bpfd-operator/controllers/bpfd-operator/tc-program.go
bpfd-operator/controllers/bpfd-operator/tracepoint-program.go
bpfd-operator/controllers/bpfd-operator/uprobe-program.go
bpfd-operator/controllers/bpfd-operator/xdp-program.go
bpfd-operator/pkg/helpers/helpers.go

All of the code assumes that only the last condition counts.  However, that's not how conditions work.  This change modifies our behavior so that we only maintain the one (most recent) condition for each program object, which is a step toward the resolution of issue #430.
Part of the solution is to create a common updateCondition() function for the bpfd-operator that is used for all program types which removes some code duplication and is a small step toward the resolution of issue #709
This also removes code duplication in xdp-program_test.go, which is a small step toward the resolution of issue #710.

Just keep one condition for each program object

---

bpfd-operator/controllers/bpfd-agent/internal/bpfd-core.go
bpfd/src/rpc.rs

Deploying BPF programs that share a map is not working in a K8s deployment. Running the examples in K8s:
```
cd bpfd/examples/
make deploy
```
See the program isn't loaded:
```
$ kubectl get xdpprograms -o yaml go-xdp-counter-sharing-map-example
apiVersion: bpfd.dev/v1alpha1
kind: XdpProgram
:
status:
conditions:
- lastTransitionTime: "2023-10-11T19:59:23Z"
message: Waiting for Program Object to be reconciled to all nodes
reason: ProgramsNotYetLoaded
status: "True"
type: NotYetLoaded
```
Logs:
```
2023-10-11T18:20:29Z	ERROR	xdp	Reconciling XdpProgram Failed	{"XdpProgramName": "go-xdp-counter-sharing-map-example", "ReconcileResult": "Requeue", "error": "failed to determine map owner: failed to get bpfd program for BpfProgram with UID 33443036-68e2-4879-920f-41a2ce371e1b: multible programs …
```

Map-sharing not working from k8s deployment

---

bpfd-operator/config/bpfd-deployment/config.yaml
bpfd-operator/config/bpfd-deployment/daemonset-csi.yaml
bpfd-operator/config/bpfd-deployment/daemonset.yaml
bpfd-operator/config/default/kustomization.yaml
bpfd-operator/config/default/patch.yaml
bpfd-operator/controllers/bpfd-operator/configmap.go
bpfd/src/bpf.rs
bpfd/src/command.rs
bpfd/src/main.rs
bpfd/src/multiprog/tc.rs
bpfd/src/multiprog/xdp.rs
bpfd/src/oci_utils/cosign.rs
bpfd/src/oci_utils/image_manager.rs
bpfd/src/utils.rs
docs/developer-guide/logging.md

Try and fixup how are logging is organized a works
This is now the logs from a load and unload of two separate programs with `RUST_LOG=bpfd=info`.
```bash
---------------->>>>>>>>> STARTUP
[astoycos@nfvsdn-02-oot bpfd]$ sudo RUST_LOG=bpfd=info ./target/debug/bpfd
[INFO  bpfd] Log using env_logger
[INFO  bpfd] Has CAP_BPF: true
[INFO  bpfd] Has CAP_SYS_ADMIN: true
[WARN  bpfd] Unable to read config file, using defaults
[INFO  bpfd::certs] CA Certificate file /etc/bpfd/certs/ca/ca.pem does not exist. Creating CA Certificate.
[INFO  bpfd::certs] bpfd Certificate Key /etc/bpfd/certs/bpfd/bpfd.key does not exist. Creating bpfd Certificate.
[INFO  bpfd::certs] bpfd-client Certificate Key /etc/bpfd/certs/bpfd-client/bpfd-client.key does not exist. Creating bpfd-client Certificate.
[INFO …
```

Fix logging

---

bpfd/src/bpf.rs
docs/developer-guide/testing.md
docs/getting-started/bpfctl-guide.md
docs/getting-started/example-bpf-local.md
docs/getting-started/tutorial.md
tests/integration-test/src/tests/basic.rs
tests/integration-test/src/tests/e2e.rs
tests/integration-test/src/tests/utils.rs

The map_used_by field is not being set properly. Each program should be listing the map it is using and all the other programs that are using it.

Fix the map_used_by field for managing the  map_pin_path

---

docs/developer-guide/operator-quick-start.md
docs/getting-started/building-bpfd.md
docs/getting-started/running-release.md
mkdocs.yml
scripts/install.sh
scripts/setup.sh

Update the documentation to include a section on how to pull and use binary images from released versions.
Fixes: #508

docs: Add Docs on how to run with release locally and in K8s

---

Cargo.toml
bpfd/Cargo.toml

Also added `features = ["tokio_socket"]` to `rtnetlink` in the bpfd `Cargo.toml` which became necessary after the title change.

workspace-ified the netlink dependencies

---

bpfd/src/bpf.rs
tests/integration-test/src/tests/e2e.rs
tests/integration-test/src/tests/utils.rs

The procceedon settings were incorrect for XDP and TC after unload and
for TC after bpfd restart.
The issue was that we were adding a program to the list before sorting 
in set_program_positions() whether we were adding, deleleting or
rebuilding.  For the later two cases this caused the actual positions
to be shifted.
Also added integration tests for the cases that caused the bug which was
a lot more work than fixing the bug itself :-).
Fixes #791

Fix Procceedon bug (Issue #791)

---

scripts/del-bpfd-qdiscs.sh

It deletes both the "clsact" and "ingress" qdiscs in an attempt to completely clean up any qdiscs and tc programs that may interfere with bpfd operation.

Add script to delete bpfd qdiscs on all interfaces

---

bpfd-operator/config/bpfd-deployment/daemonset.yaml

Add an init container to mount the default bpffs if it doesn't exist. This mostly occurs with kind.

bpfd: mount default bpffs on kind

---

.github/workflows/build.yml

add musl-tools to our github runers so we can build a static binary for our release artifacts.
https://github.com/bpfd-dev/bpfd/actions/runs/6961278822/job/18942543161

bpfd: fix release build

---

docs/getting-started/building-bpfd.md

When installing rust using rustup, it already creates an environment
file for adding cargo binaries to the path and there's no need to
expliticly export it again.

Correct cargo path

---

Cargo.lock
Cargo.toml
bpf-metrics-exporter/Cargo.toml
bpf-metrics-exporter/README.md
bpf-metrics-exporter/metrics-stack.yaml
bpf-metrics-exporter/src/main.rs

This commit adds a sample bpf-metrics-exporter.
This currently just reads programs that are loaded into the kernel and exports the metrics (at a 5s interval) to an OTEL-gRPC endpoint.
There is some documentation and a sample metrics stack attached for visualising this information.
fixes #578

bpf-metrics-exporter: Add metrics exporter

---

.github/workflows/build.yml
Cargo.lock
Cargo.toml
bpfman/Cargo.toml
bpfman/src/bpf.rs
bpfman/src/oci_utils/image_manager.rs
bpfman/src/serve.rs
bpfman/src/storage.rs
scripts/bpfman.service
scripts/bpfman.socket
scripts/install.sh
scripts/setup.sh

When loading bpfman as a systemd service, implement socket activation. Socket activation is a systemd feature in which a given service is not started until it is needed, in this case, a request is received on a socket. To reduce the attack surface, it is preferred that bpfman not run forever, but instead stop after a period of inactivity. The current
implementation has a hard stop of bpfman after 15 seconds. Trying to restart timers over multiple async threads was not worth the effort since async nature of bpfman is going to be ripped out over the nextcouple of weeks.
NOTE: Systemd can support stopping a service after a specified time of inactivity. But it requires the builtin systemd proxy, where systemd listens on the primary socket and when a request comes in the request is sent to …

bpfman: add support for socket activation

---

Cargo.lock
bpfman-api/src/lib.rs
bpfman/Cargo.toml
bpfman/src/bpf.rs
bpfman/src/cli/system.rs
bpfman/src/command.rs
bpfman/src/errors.rs
bpfman/src/main.rs
bpfman/src/multiprog/mod.rs
bpfman/src/multiprog/tc.rs
bpfman/src/multiprog/xdp.rs
bpfman/src/rpc.rs
bpfman/src/serve.rs
bpfman/src/static_program.rs
bpfman/src/storage.rs
bpfman/src/utils.rs

Works towards #860 
This commit is huge and it re-writes the memory layout for all Program
related information. More specifically it removed the KernelInfo struct
and collapses all information for bpfman programs AND other programs
into a single Program enum. This program Enum is essentially a wrapper
for a sled database tree. Each program will get it's own sled database tree
and anytime a getter/setter is called on a Program it will interact with
the database.
Special considerations: 
- On load we have to use a random number generator to generate a unique id
for the program tree prior to load.  Once the program is successfully
loaded we can then swap the root index of the database tree to the
correct id.  From then on it's always safe to assume the tree name will
correlate to a given …

Sled integration for the core program type

---

Containerfile.bpfman
Containerfile.bpfman.local
bpfman/src/bpf.rs
bpfman/src/cli/args.rs
bpfman/src/cli/get.rs
bpfman/src/cli/image.rs
bpfman/src/cli/list.rs
bpfman/src/cli/load.rs
bpfman/src/cli/mod.rs
bpfman/src/cli/system.rs
bpfman/src/cli/unload.rs
bpfman/src/main.rs
bpfman/src/oci_utils/image_manager.rs
bpfman/src/serve.rs
bpfman/src/storage.rs
tests/integration-test/src/tests/utils.rs

1. Removes custom Tokio runtime construction
2. Uses a broadcast channel for the shutdown handler so each of the "managers" may recieve the message and shutdown.

Tidy up async code and shutdown handling

---

docs/blog/posts/sled-integration.md
mkdocs.yml

Fix this failure I saw in CI 
```
mike deploy --push main
shell: /usr/bin/bash -e {0}
env:
pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/bpfman/bpfman/actions/runs/7613204594/job/20732554473#step:10:3).8.18/x6[4](https://github.com/bpfman/bpfman/actions/runs/7613204594/job/20732554473#step:10:4)
PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.18/x[6](https://github.com/bpfman/bpfman/actions/runs/7613204594/job/20732554473#step:10:6)4/lib/pkgconfig
Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.[8](https://github.com/bpfman/bpfman/actions/runs/7613204594/job/20732554473#step:10:8).18/x64
Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
INFO    - …
```

add daemonless doc to website fixup sled article 

---

.github/workflows/build.yml
Cargo.lock
bpfman/src/cli/args.rs
docs/getting-started/building-bpfman.md
scripts/install.sh
scripts/setup.sh
xtask/src/build_completion.rs
xtask/src/build_ebpf.rs
xtask/src/build_manpage.rs
xtask/src/copy.rs
xtask/src/main.rs
xtask/src/protobuf.rs
xtask/src/workspace.rs

There are a couple of nits in the CLI manpage and tab-completion generation. This PR addresses most of them.
* Document how to build and install. It's not obvious how to install the generated files.
* We tend not to use environment variables to build bpfman. Moved OUT_DIR to a fixed location.
* Only top level manpages are generated. `man bpfman get` and `man bpfman list` are implemented, but those with subcommands, primarily `man bpfman load`, don't document any of the subcommand parameter or usage.
* Update the install scripts/setup.sh to copy the generated files, if they have been generated. Remove them on uninstall.
* Call the new xtask commands in CI
Not completed:
* Add the generated files to the RPM build
* To show the load subcommands, hyphens are required, this should be fixed: …

cli: fix nits in manpage and tab-completion

---

bpfman-api/src/util.rs
bpfman-operator/config/bpfman-deployment/daemonset.yaml
bpfman-operator/internal/constants.go
docs/getting-started/running-rpm.md
examples/pkg/config-mgmt/configfile.go
scripts/bpfman.socket
scripts/setup.sh
scripts/user.sh

On a redeploy of bpfman in a Kubernetes deployment (for example, edit the bpfman ConfigMap and change one of the log level values), bpfman fails to come back up. `/run/bpfman/sock/` is defined in the bpfman-deployment as an empty-dir, but on a restart, `/run/bpfman/` is remounted, but contains a non-empty `/run/bpfman/sock/` directory. This causes the container not to come up.
The fix is to rename `/run/bpfman/sock/bpfman.sock` to `/run/bpfman-sock/bpfman.sock`.
To reproduce:
```
kubectl edit configmap -n bpfman bpfman-config
apiVersion: v1
data:
bpfman.agent.image: quay.io/bpfman/bpfman-agent:latest
bpfman.agent.log.level: info
bpfman.image: quay.io/bpfman/bpfman:latest
bpfman.log.level: info -> debug
:
kubectl describe pod -n bpfman bpfman-daemon-sb95t
:
Events:
Type     Reason     Age …
```

bpfman: move bpfman.sock to standalone directory

---

docs/developer-guide/operator-quick-start.md
docs/getting-started/building-bpfman.md
docs/getting-started/tutorial.md

Fix some minor nits in docs. Primarily, when running as a long running process, use `bpfman system service --timeout=0`. ﻿﻿Also add docker and kind to the list of packages that may need to be installed.

docs: Minor nits

---

bpfman/src/cli/args.rs
bpfman/src/cli/system.rs
bpfman/src/serve.rs
bpfman/src/storage.rs
bpfman/src/utils.rs

Make the socket bpfman listen's on configurable. This isn't currently useful for the CLI since the socket can't be configured there, but for external users like the bpfman-agent it is.
Follow up to #962

bpfman: Make the listening socket configurable

---

.github/workflows/build.yml

Temporarily drop the rust-cache action since it just hangs following it's run, we'll need to go back and re-activate this at some point

DROP: Temporarily drop  rust-cache action

---

.github/workflows/build.yml

Upstream main builds have been failing:
```
Run cd bpfman-operator && make bundle
:
go: downloading golang.org/x/text v0.5.0
/home/runner/work/bpfman/bpfman/bpfman-operator/bin/controller-gen crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
controllers/bpfman-agent/common.go:25:2: package slices is not in GOROOT (/opt/hostedtoolcache/go/1.20.13/x64/src/slices)
Error: not all generators ran successfully
run `controller-gen crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -w` to see all available markers, or `controller-gen crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -h` for usage
make: *** [Makefile:192: manifests] Error 1
```
The error mentions `/opt/hostedtoolcache/go/1.20.13/x64/src/slices` but I believe slices package …

build: set golang to 1.21 for github builds

---

bpfman/src/bpf.rs
bpfman/src/command.rs
bpfman/src/multiprog/mod.rs
bpfman/src/multiprog/tc.rs
bpfman/src/multiprog/xdp.rs

Add prefixes to the program tree names in sled and remove the erroneous id structure field which was no longer needed.
Still need to

sled fixups and prefixes for final conversion bits

---

bpfman-operator/cmd/bpfman-agent/main.go
bpfman-operator/cmd/bpfman-operator/main.go
bpfman-operator/config/bpfman-deployment/config.yaml
bpfman-operator/config/bpfman-deployment/daemonset.yaml
bpfman-operator/config/bpfman-operator-deployment/deployment.yaml
bpfman-operator/config/default/manager_auth_proxy_patch.yaml
bpfman-operator/config/openshift/manager_auth_proxy_patch.yaml
bpfman-operator/config/test/manager_auth_proxy_patch.yaml
bpfman-operator/controllers/bpfman-operator/configmap.go
bpfman-operator/internal/constants.go
docs/developer-guide/debugging.md
docs/developer-guide/develop-operator.md
docs/developer-guide/logging.md

In some scenarios, the health and metric ports may are already in use by other services on the system. When this happens the bpfman-agent container fails to deploy. The current default is 8080 and 8081. First, move the port numbers to something less common. Then make the values configurable.
The ports are passed in through the yaml files. However, the bpfd-agent releated yaml files are built into the bpfman-operator image, so the values cannot be easily changed without rebuilding the image. So add fields to the ConfigMap so they can be overwritten without rebuilding the bpfman-operator image.
Resolves: #914

operator: make health and metrics ports configurable

---

.github/workflows/build.yml
.github/workflows/image-build.yaml

Upstream main builds have been failing:
```
Run cd bpfman-operator && make bundle
:
go: downloading golang.org/x/text v0.5.0
/home/runner/work/bpfman/bpfman/bpfman-operator/bin/controller-gen crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
controllers/bpfman-agent/common.go:25:2: package slices is not in GOROOT (/opt/hostedtoolcache/go/1.20.13/x64/src/slices)
Error: not all generators ran successfully
run `controller-gen crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -w` to see all available markers, or `controller-gen crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -h` for usage
make: *** [Makefile:192: manifests] Error 1
```
The error mentions `/opt/hostedtoolcache/go/1.20.13/x64/src/slices` but I believe slices package …

build: make bundle failing on upstream main

---

.github/workflows/build.yml
Cargo.lock
Cargo.toml

curve25519-dalek fixed their clippy errors and released 4.1.2. So revert the pin to nightly-2024-02-03 and moved back to nightly.
Resolves: #977

build: revert back to nightly

---

.github/workflows/build.yml

If uploads still regularly fail we might wish to consider another service for code coverage.

ci: Don't fail the build on codecov

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/docs-build.yaml
.github/workflows/image-build.yaml
.packit.yml
.yamllint.yaml
bpfman-operator/config/bpfman-deployment/config.yaml
bpfman-operator/config/bpfman-deployment/daemonset.yaml
bpfman-operator/config/bpfman-operator-deployment/deployment.yaml
bpfman-operator/config/default/manager_auth_proxy_patch.yaml
bpfman-operator/config/openshift/manager_auth_proxy_patch.yaml
bpfman-operator/config/openshift/patch.yaml
bpfman-operator/config/samples/bpfman.io_v1alpha1_uprobe_uprobeprogram_containers.yaml
bpfman-operator/config/samples/bpfman.io_v1alpha1_uprobe_uprobeprogram_nginx.yaml
bpfman-operator/config/test/manager_auth_proxy_patch.yaml
examples/config/v0.2.0/go-tc-counter/kustomization.yaml
examples/config/v0.2.0/go-tracepoint-counter/kustomization.yaml
examples/config/v0.2.0/go-xdp-counter/kustomization.yaml
examples/config/v0.3.0/go-tc-counter/kustomization.yaml
examples/config/v0.3.0/go-tracepoint-counter/kustomization.yaml
examples/config/v0.3.0/go-xdp-counter-sharing-map/kustomization.yaml
examples/config/v0.3.0/go-xdp-counter/kustomization.yaml
examples/config/v0.3.1-ocp/go-tc-counter/patch.yaml
packaging/vm-deployment/provision.yaml

Tell yamllint to prefer double quotes + nag on unnecessary quotes. Tell prettier (used in vscode-yaml) to ignore the golang versions, that are in single quotes due to "1.20" being shortened to 1.2, which has strange results.

chore: Fix yamllint/vscode-yaml formatting discrepencies

---

Containerfile.bpfman.local

Stop building ebpf bytecode as part of the core
bpfman image build process, since now the dispatcher bytecode is pulled from OCI images.
Super small change, but I'm seeing a dramatic decrease in build time by removing some dependencies! 
BEFORE 221.0 seconds fresh build
```bash
[astoycos@nfvsdn-02-oot bpfman]$ DOCKER_BUILDKIT=1 docker build -f Containerfile.bpfman.local  .
[+] Building 221.0s (21/21) FINISHED                                                                                                                                                          
=> [internal] load .dockerignore                                                                                                                                                        0.0s
=> => transferring context: 65B …
```

speed up bpfman image build

---

bpfman-api/src/config.rs
bpfman-api/src/lib.rs

Implement std::fmt::Display rather than to_string
for Location and XDPMode to fix clippy failures.

remove to-string clippy failures

---

bpfman/src/bpf.rs
bpfman/src/serve.rs
bpfman/src/utils.rs

Make sure bpfman state is rebuilt before starting
the unix server, since data is intially written
in rpc.rs it could race with the rebuilding state
in bpfmanager::rebuild_state().
In this particular scenario, when running with
systemd, a `ProgramData` temporary pre-load
database tree would get created before the rebuild_state() was called, and then the rebuild logic would
delete the `ProgramData` tree mid load causing
all of the loading errors.

fix startup race

---

bpfman-api/src/util.rs
bpfman/src/cli/system.rs
bpfman/src/oci_utils/cosign.rs

This writes the TUF metadata to disk instead of caching in-memory. This should allow for multiple invocations of bpfman to be faster.

bpfman: Cache TUF Metadata

---

bpfman/src/bpf.rs
bpfman/src/cli/get.rs
bpfman/src/cli/image.rs
bpfman/src/cli/list.rs
bpfman/src/cli/load.rs
bpfman/src/cli/mod.rs
bpfman/src/cli/system.rs
bpfman/src/cli/unload.rs
bpfman/src/command.rs
bpfman/src/rpc.rs
bpfman/src/storage.rs
tests/integration-test/src/tests/basic.rs
tests/integration-test/src/tests/e2e.rs
tests/integration-test/src/tests/utils.rs

I decided to tackle this in one PR to not have a ton of intermediary hacks in the integration tests, and it really shouldn't be too big of a PR. (load will be the most difficult)
Fixes #936 #937 #938 #939 #940 #941 #942 #943 #944 #945 #946 #947 #948 #949 #950 #952

Convert the rest of the cli to not use GRPC

---

CONTRIBUTING.md
MAINTAINERS.md
README.md
REVIEWING.md
changelogs/CHANGELOG-v0.3.1.md
docs/blog/posts/introduction-to-bpfman.md
docs/blog/posts/sled-integration.md
docs/developer-guide/documentation.md

I think the main issue was that the [Setup and Building bpfman](https://bpfman.io/getting-started/building-bpfman/) link in README.md was broken.
If you just try to got to bpfman.io, it sends you to the "main" version.  However, if you use bpfman.io with the path to a specific page without a version in the URL, the link defaults to v0.3.1, and the building-bpfman page has moved since then.
For a fix, I added "/main" in the links so they will go to the latest version of the website.  If we leave it this way, I think we'll want to update that to the released version when we release the code.  mkdocs mike won't do this for us, so we could create a script to do it.  Another alternative is to make them relative links to the actual md files, but I think the goal is to send people to our website …

Fix broken links in docs

---

bpfman-operator/apis/v1alpha1/bpfprogram_types.go
bpfman-operator/apis/v1alpha1/kprobeProgram_types.go
bpfman-operator/apis/v1alpha1/tcProgram_types.go
bpfman-operator/apis/v1alpha1/tracepointProgram_types.go
bpfman-operator/apis/v1alpha1/uprobeProgram_types.go
bpfman-operator/apis/v1alpha1/xdpProgram_types.go
bpfman-operator/config/crd/bases/bpfman.io_bpfprograms.yaml
bpfman-operator/config/crd/bases/bpfman.io_kprobeprograms.yaml
bpfman-operator/config/crd/bases/bpfman.io_tcprograms.yaml
bpfman-operator/config/crd/bases/bpfman.io_tracepointprograms.yaml
bpfman-operator/config/crd/bases/bpfman.io_uprobeprograms.yaml
bpfman-operator/config/crd/bases/bpfman.io_xdpprograms.yaml
bpfman-operator/hack/kubectl-bpfprogramconfigs
bpfman-operator/hack/kubectl-bpfprograms

The `kubectl-bpfprogramconfigs` and `kubectl-bpfprograms` files located in `bpfman-operator\hack\` were used to customize the `kubectl get` output for the bpfman CRD objects. A while back, the code moved to use kubebuilder to autogenerate similar output, making these files outdated. So remove these files.
Now that each of the status slices in the bpfman CRD objects only contains one instance, add the status.reason to the `kubectl get` output for each of the bpfman CRD objects. For `kubectl get bpfprograms`, also add `Type`.
```
$ kubectl get tcprograms
NAME                    BPFFUNCTIONNAME   NODESELECTOR   STATUS
go-tc-counter-example   stats             {}             ReconcileSuccess
$ kubectl get tracepointprograms
NAME                            BPFFUNCTIONNAME …
```

bpfman-operator: Add status to kubectl get commands

---

bpfman/src/bpf.rs
bpfman/src/cli/image.rs
bpfman/src/cli/mod.rs
bpfman/src/cli/system.rs
bpfman/src/command.rs
bpfman/src/main.rs
bpfman/src/multiprog/mod.rs
bpfman/src/multiprog/tc.rs
bpfman/src/multiprog/xdp.rs
bpfman/src/oci_utils/image_manager.rs
bpfman/src/rpc.rs
bpfman/src/serve.rs
bpfman/src/storage.rs
bpfman/src/utils.rs

Refactor the image manager
- Remove all channels and commands
- only initialize image_manager when needed and do this in the core codepath (bpf.rs)
- Cleanup a bunch of extra async functions which don't need to be async any longer

Image manager refactor

---

docs/blog/posts/ebpf-container-challenges.md

From the doc:
We recently added support for attaching uprobes in containers.  The purpose of
this blog is to document the technical challenges encountered and solutions for
those challenges. In particular, how do you attach an eBPF program inside of a
container, and how do you find the host Process ID (PID) on the node for the
container?
Fixes: #1019

blog: uprobe in container work

---

Cargo.lock
Containerfile.bpfman
Containerfile.bpfman.local
bpfman.spec
bpfman/Cargo.toml

In order to be more easily packaged by Linux distros, we'll opt to use native-tls over rust-tls. This puts a compile-time dependency on having openssl libraries/headers available. This requires changes to the Dockerfile and Specfile.
This also drops support for musl libc - given that figuring out how to cross-compile OpenSSL for musl is a pain.
Therefore, we move away from using a `scratch` image to a RHEL UBI image, which does include libc. Given this image includes microdnf we can drop the bpfman.local image and install debugging tools on demand.

chore(bpfman): Use native-tls

---

.github/workflows/build.yml
CONTRIBUTING.md
Cargo.lock
Cargo.toml
xtask/Cargo.toml
xtask/public-api/bpfman-api.txt
xtask/public-api/bpfman-csi.txt
xtask/public-api/bpfman.txt
xtask/src/main.rs
xtask/src/public_api.rs

Now that bpfman is officially a library this adds
a public api check to ensure that changes to our
public api are tightly controlled and explicitly
"blessed" by contributors.  It will maintain
public api text files for the bpfman, bpfman-api,
and bpfman-csi library crates.
Fixes #1036

add public-api checks

---

CONTRIBUTING.md
scripts/lint.sh
scripts/setup.sh
scripts/verify-golint.sh
xtask/src/lint.rs
xtask/src/main.rs
xtask/src/unit_test.rs

```shell
cargo xtask -h
Finished dev [unoptimized + debuginfo] target(s) in 0.20s
Running `target/debug/xtask -h`
Usage: xtask <COMMAND>
Commands:
build-ebpf        Build the eBPF bytecode for programs used in the integration tests
build-proto       Build the gRPC protobuf files
copy              Prep the system for using bpfman by copying binaries to "/usr/sbin/"
run               Run bpfman on the local host
integration-test  Run the integration tests for bpfman
build-man-page    Build the man pages for bpfman
build-completion  Build the completion scripts for bpfman
lint              Run the linter
help              Print this message or the help of the given subcommand(s)
Options:
-h, --help     Print help
-V, --version  Print version
```

Add xtask rules to run lint and ut

---

.github/workflows/build.yml
changelogs/CHANGELOG-v0.4.0.md

Make sure to publish the bpfman-csi and bpfman-rpc crates before doing the core bpfman one since
they are dependencies.

small v0.4.0 release fixes

---

Cargo.lock
bpf-log-exporter/Cargo.toml

make sure the bpf-log-exporter compiles independently of the workspace and run cargo generate-lockfile.

cargo updates

---

bpfman-api/src/bin/rpc/main.rs
bpfman-api/src/bin/rpc/serve.rs
bpfman/src/bin/cli/main.rs
bpfman/src/lib.rs
bpfman/src/utils.rs
docs/developer-guide/logging.md
docs/getting-started/launching-bpfman.md
docs/getting-started/running-release.md

When running bpfman as a long running process, bpfman-rpc fails to run because directory /run/bpfman-sock is not created.
```
$ sudo RUST_LOG=info ./target/debug/bpfman-rpc --timeout=0
Error: No such file or directory (os error 2)
```
Second issue is that no logs are generated when bpfman-rpc is run.
As part of the rework of bpfman recently, the creation of /run/bpfman-sock was moved from bpfman to bpfman-rpc, but it was inadvertantly moved to a CSI only check. The fix is to move it out of the CSI only logic.
Now that bpfman core is a library, all log initialization should occur in the calling binary. So move the log initialization to bpfman-rpc and bpfman CLI.
Resolves: #1077

bpfman: dir bpfman-sock missing for bpfman-rpc

---

Cargo.lock
bpfman-api/src/bin/rpc/storage.rs
examples/config/base/go-kprobe-counter/deployment.yaml
examples/config/base/go-tc-counter/deployment.yaml
examples/config/base/go-tracepoint-counter/deployment.yaml
examples/config/base/go-uprobe-counter/deployment.yaml
examples/config/base/go-xdp-counter/deployment.yaml

Add support for our CSI driver to be able to
assign a passed fsGroup value to the mounted bpffs. see https://kubernetes-csi.github.io/docs/support-fsgroup.html for more.
This allows unprivileged applications to access
those pin points when configured correctly
with `fsGroup`, `runAsUser`, and `runAsGroup` for
a kubernetes workload.
A First step in #596 
this also adresses a bunch of small formatting things

add csi fsgroup support

---

.licenserc.yaml
bpfman/LICENSE-APACHE

This PR includes the licenses files in the crate workspace subdirectory.
Without this, they won't be showing on crates.io and would be giving out
errors on tooling such as rust2rpm.

bpfman: include license in crate workspace

---

bpfman.spec
scripts/install.sh

bpfman-rpc and bpfman-ns are not currently in the bpfman RPM. Add both binaries.
Resolves: #1095

rpm: Add bpfman-rpc and bpfman-ns to rpm package

---

docs/getting-started/building-bpfman.md
docs/getting-started/example-bpf-local.md
docs/getting-started/example-bpf.md
examples/go-kprobe-counter/main.go
examples/go-tc-counter/main.go
examples/go-tracepoint-counter/main.go
examples/go-uprobe-counter/main.go
examples/go-uretprobe-counter/main.go
examples/go-xdp-counter/main.go
go.mod
go.sum

- fixes issue #1080 
- update apt-based OS instructions to install missing packages for bpfman development, as per Ubuntu 23.10.
- as per [cilium/ebpf examples](https://github.com/cilium/ebpf/tree/main/examples) use "go run" and the full import path of the bpf2go tool in order to avoid developers having to explicitly install bpf2go; this way, the tool is automatically pulled and build if not present in Go's cache.
- document the more Go idiomatic use of `go run -exec sudo . ...` instead of `sudo ./go-... ...`, as users can immediately run an example without having to explicitly build everything first.

Examples/Docs: idiomatic Go usage and update installation instructions for apt-based OS

---

.github/workflows/image-build.yaml
examples/build-bytecode-images.sh
tests/integration-test/bpf/build_push_images.sh

go-uretprobe-counter, from the examples directory, and fentry/fexit from the integration-tests directory, are not being pushed to quay.io automatically because they are missing from image-build.yaml. So add those images.
While there, noticed that PROGRAM_TYPE is being used inconsistently. Sometimes uprobe uses kprobe and sometimes it uses uprobe. Made them consistent with image type (kprobe, kretprobe, uprobe, uretprobe).

image: Add missing images to push to quay

---

bpfman-operator/config/bpfman-deployment/daemonset.yaml

Fix the image we use to mount the default bpffs
if it's not mounted (i.e kind) to fedora 39 since
the newer fedora-minimal images don't have the
mount binary by default.

fix mounter image to fedora 39

---

bpfman/src/utils.rs
tests/integration-test/src/tests/basic.rs
tests/integration-test/src/tests/e2e.rs
tests/integration-test/src/tests/error.rs
tests/integration-test/src/tests/mod.rs
tests/integration-test/src/tests/utils.rs

Add tests to the integration test suite for invalid input and verify bpfman handles it correctly and does not panic.

test: add negative test cases to integration tests

---

.github/workflows/build.yml
bpfman-operator/config/samples/bpfman.io_v1alpha1_uprobe_uprobeprogram.yaml
bpfman-operator/controllers/bpfman-agent/common.go
bpfman-operator/controllers/bpfman-agent/fentry-program.go
bpfman-operator/controllers/bpfman-agent/fexit-program.go
bpfman-operator/controllers/bpfman-agent/kprobe-program.go
bpfman-operator/controllers/bpfman-agent/tc-program.go
bpfman-operator/controllers/bpfman-agent/tracepoint-program.go
bpfman-operator/controllers/bpfman-agent/uprobe-program.go
bpfman-operator/controllers/bpfman-agent/xdp-program.go
bpfman-operator/controllers/bpfman-operator/fentry-program.go
bpfman-operator/controllers/bpfman-operator/fexit-program.go
bpfman-operator/controllers/bpfman-operator/kprobe-program.go
bpfman-operator/controllers/bpfman-operator/tc-program.go
bpfman-operator/controllers/bpfman-operator/tracepoint-program.go
bpfman-operator/controllers/bpfman-operator/uprobe-program.go
bpfman-operator/controllers/bpfman-operator/xdp-program.go
bpfman-operator/internal/constants.go
examples/Makefile

- Created a common loop for reconciling *Programs
- Created a common reconcileBpfmanProgram() function
- Added some more getters to the bpfmanReconciler interface so we don't have to pass as many parameters around
- Made all of the functions in common.go that use ReconcilerCommon methods of ReconcilerCommon
Some additional changes:
- Used a different Type in the BpfProgram CRDs for fentry and fexit. With this change, the fentry and fexit controllers will only get triggered for the their own programs, and you can see the type when you get the bpfprogram CRD.
- Modified Makefile in examples
- Made building go userspace code and bytecode dependencies of their respective build-*-image targets
- Added a target to build-all-images
- This combines 4 steps into one if you want to build both …

De-duplicate code in the bpfman-agent

---

docs/developer-guide/k8s-selinux-distros.md
mkdocs.yml
tests/integration-test/src/tests/basic.rs
tests/integration-test/src/tests/e2e.rs
tests/integration-test/src/tests/error.rs
tests/integration-test/src/tests/utils.rs

Adding one additional test to integration error test cases. For loading from image, if no name is provided, use name from OCI Image. If name is provided, use that instead. So added a test to pass in an invalid name from CLI when laoding from image and make sure command fails.
Also global changed all forms of selinux to SELinux.

test: add image name test

---

.github/workflows/build.yml

PR #1068 attempted to do this, in part, by creating a separate `get-more-space` job, but since each job runs in its own runner, the `get-more-space` job didn't help.  This PR moves some of the `get-more-space` steps into the `kubernetes-integration-tests` job.
The solution in this pr is much better than the one in #1068 because all I had to do was delete some unneeded directories in the `kubernetes-integration-tests` job.  This is much faster and still frees up plenty of disk space.

Free up disk space for running k8s int tests

---

.packit.yml

So far we're still proposing the package to be acceptef on Fedora, so
this job would just fail. Let's remove it until we get the package in
and it gets accepted.

Remove propose_downstream packit job

---

.packit.sh
.packit.yml
Cargo.lock
Cargo.toml
bpfman.spec
changelogs/CHANGELOG-v0.4.1-rc1.md
changelogs/CHANGELOG-v0.4.1-rc2.md

Specifically
- Start pushing to [bpfman](https://copr.fedorainfracloud.org/coprs/g/ebpf-sig/bpfman/) on releases while still pushing to [bpfman-next](https://copr.fedorainfracloud.org/coprs/g/ebpf-sig/bpfman/) on every commit to main.
- Ensure that the specfile Release tag is not overridden when the release triggers a copr_build.
- make the logic in .packit.sh more reliable by always overriding values regardless of what's happening locally on disk.

cut an rc2 to ensure our rpm builds are working

---

.github/workflows/build.yml
.packit.yml
Cargo.lock
Cargo.toml
changelogs/CHANGELOG-v0.4.1-rc4.md

Cut a v0.4.1-rc4 release
- Fixup the publish crate action
- fixup packit.yml one last time since we need a custom set of actions when building for a release unfortunately this means we need to copy ALL of the actions since they get overridden.

cut a rc4 release

---

.packit.sh

fix a bug where packit RPM builds we're failing
when pre-releases are not set.

make sure packit does not fail

---

Cargo.lock
Cargo.toml
bpf-log-exporter/Cargo.toml
bpf-metrics-exporter/Cargo.toml
bpfman-api/Cargo.toml
bpfman-ns/Cargo.toml
bpfman.spec
bpfman/Cargo.toml
csi/Cargo.toml
tests/integration-test-macros/Cargo.toml
tests/integration-test/Cargo.toml
xtask/Cargo.toml

A bunch of fixes based on the feedback in https://bugzilla.redhat.com/show_bug.cgi?id=2269411
- I we need to patch `ring v0.17.8` and `sigstore-protobuf-specs` crates since they don't specify any license metadata. I didn't do it here since we don't maintain a version of the vendor tarball in github

RPM fixes 

---

bpfman/src/lib.rs

Currently `bpfman` will panic when DatabaseLockError occurred.
```
thread 'main' panicked at /root/go/src/github.com/bpfman/bpfman/bpfman/src/lib.rs:486:14:
Unable to open root database: DatabaseLockError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After this patch `bpfman` will print DatabaseLockError message and don't panic
```
Error: Failed to acquire database lock, please try again later
```
Refs: #1018

bpfman: don't panic if DatabaseLockError occurred

---

bpfman/src/config.rs
bpfman/src/lib.rs

The description for max_retries is "Maximum number of times to attempt to open the database after a failed attempt". However, the way the for loop is implemented, bpfman actually makes max_retries-1 attempts. For example, if you set it to 1, we try 0 times and fail immediately without trying.
Fixes: #1145

Make DatabaseConfig max_retries work as defined.

---

docs/getting-started/running-rpm.md
docs/quick-start.md

The RPM spec file is being updated to be compliant with Fedora (see #1146). One of the changes requires bpfman to be stopped before uninstalling the RPM, otherwise errors are logged and reinstall of the RPM fails.
Example Error:
```
May 21 10:41:49 nfvsdn-22-oot.lab.eng.rdu2.redhat.com systemd[1]: bpfman.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.
```
And subsequent RPM install fails and bpfman is not running:
```
$ sudo ./go-xdp-counter --iface eno3
2024/05/21 11:03:28 Using Input: Interface=eno3 Priority=50 Source=/home/bmcfall/src/bpfman/examples/go-xdp-counter/bpf_bpfel.o
2024/05/21 11:03:28 rpc error: code = Unavailable desc = connection error: desc = "transport: …
```

docs: update the RPM uninstall process

---

Cargo.lock
Cargo.toml

Bump the public-api crate so that our checks
still function.

fix public-api check

---

bpfman/src/types.rs

The BpfApplication CRD support is intended to allow an application to define a set of BPF programs required for operation.  This set of programs may included multiple types of BPF programs that are packaged in a single .o and single bytecode image file.  However, our currentl image spec is designed to support a single bpf program with a single type.
More importantly, the bpfman code has a check to validate that the name of program being loaded matches the name that is provided by the user.
As a temporary work-around, this pr just logs the mismatch and doesn't fail the load.
A more complete solution will be provided by pr #1141

Temporary work-around for multi-program container images

---

.github/workflows/build.yml
Cargo.lock
Cargo.toml
RELEASE.md
bpfman-operator/Makefile
changelogs/CHANGELOG-v0.4.2.md
docs/getting-started/running-release.md
docs/quick-start.md
examples/config/v0.4.2-selinux/go-kprobe-counter/kustomization.yaml
examples/config/v0.4.2-selinux/go-target/kustomization.yaml
examples/config/v0.4.2-selinux/go-tc-counter/kustomization.yaml
examples/config/v0.4.2-selinux/go-tracepoint-counter/kustomization.yaml
examples/config/v0.4.2-selinux/go-uprobe-counter/kustomization.yaml
examples/config/v0.4.2-selinux/go-uretprobe-counter/kustomization.yaml
examples/config/v0.4.2-selinux/go-xdp-counter-sharing-map/kustomization.yaml
examples/config/v0.4.2-selinux/go-xdp-counter/kustomization.yaml
examples/config/v0.4.2/go-kprobe-counter/kustomization.yaml
examples/config/v0.4.2/go-target/kustomization.yaml
examples/config/v0.4.2/go-tc-counter/kustomization.yaml
examples/config/v0.4.2/go-tracepoint-counter/kustomization.yaml
examples/config/v0.4.2/go-uprobe-counter/kustomization.yaml
examples/config/v0.4.2/go-uretprobe-counter/kustomization.yaml
examples/config/v0.4.2/go-xdp-counter-sharing-map/kustomization.yaml
examples/config/v0.4.2/go-xdp-counter/kustomization.yaml
xtask/public-api/bpfman.txt

Cut a patch release to pull in some operator-olm
fixes (not shown here), prior to merging the bpf-application changes which will require a 0.5.0 release

cut a v0.4.2 patch release

---

examples/.gitignore
examples/config/default/go-kprobe-counter/patch.yaml
examples/config/default/go-tc-counter/patch.yaml
examples/config/default/go-tracepoint-counter/patch.yaml
examples/config/default/go-uprobe-counter/patch.yaml
examples/config/default/go-uretprobe-counter/patch.yaml
examples/config/default/go-xdp-counter-sharing-map/patch.yaml
examples/config/default/go-xdp-counter/patch.yaml
examples/config/selinux/go-kprobe-counter/patch.yaml
examples/config/selinux/go-tc-counter/patch.yaml
examples/config/selinux/go-tracepoint-counter/patch.yaml
examples/config/selinux/go-uprobe-counter/patch.yaml
examples/config/selinux/go-uretprobe-counter/patch.yaml
examples/config/selinux/go-xdp-counter-sharing-map/patch.yaml
examples/config/selinux/go-xdp-counter/patch.yaml

The patch.yaml files were removed from the examples/config directory in PR#1161. They were removed because they are generated by the Makefile. However, bpfman-operator/tests/integration calls Kustomize directly and is not going through the Makefile. So add them back.

examples: Add patch.yaml file back

---

.github/workflows/image-build.yaml
docs/getting-started/example-bpf.md
examples/Makefile
examples/build-bytecode-images.sh
examples/config/base/go-app-counter/bytecode.yaml
examples/config/base/go-app-counter/deployment.yaml
examples/config/base/go-app-counter/kustomization.yaml
examples/config/default/go-app-counter/kustomization.yaml
examples/config/default/go-app-counter/patch.yaml
examples/config/default/go-app-counter/patch.yaml.env
examples/go-app-counter/.gitignore
examples/go-app-counter/bpf/app_counter.c
examples/go-app-counter/bpf/kprobe_counter.h
examples/go-app-counter/bpf/tc_counter.h
examples/go-app-counter/bpf/tracepoint_counter.h
examples/go-app-counter/bpf/uprobe_counter.h
examples/go-app-counter/bpf/xdp_counter.h
examples/go-app-counter/container-deployment/Containerfile.go-application-counter
examples/go-app-counter/kprobe_main.go
examples/go-app-counter/main.go
examples/go-app-counter/tc_main.go
examples/go-app-counter/tracepoint_main.go
examples/go-app-counter/uprobe_main.go
examples/go-app-counter/xdp_main.go
examples/pkg/config-mgmt/param.go

Add application object example
```sh
make deploy-target
IMAGE_APP_BC="quay.io/mmahmoud/bpfman-bytecode/go-application-counter:all" make deploy-application
oc get bpfprograms
NAME                                                                                                            TYPE          STATUS         AGE
go-application-counter-example-kprobe-bpfman-deployment-control-plane-try-to-wake-up                            application   bpfmanLoaded   50s
go-application-counter-example-tc-bpfman-deployment-control-plane-eth0                                          application   bpfmanLoaded   40s
go-application-counter-example-tracepoint-bpfman-deployment-control-plane-syscalls-sys-enter-kill               application   bpfmanLoaded   45s …
```

Add application object example

---

.github/workflows/image-build.yaml
docs/getting-started/example-bpf.md
examples/Makefile
examples/config/base/go-app-counter/bytecode.yaml
examples/config/base/go-app-counter/deployment.yaml
examples/config/default/go-app-counter/kustomization.yaml
examples/config/default/go-app-counter/patch.yaml
examples/go-app-counter/container-deployment/Containerfile.go-app-counter
examples/go-app-counter/main.go
examples/pkg/config-mgmt/param.go

```sh
oc get pods -n go-app-counter
NAME                      READY   STATUS    RESTARTS   AGE
go-app-counter-ds-cv5wc   1/1     Running   0          35s
oc describe pods -n go-app-counter
Name:             go-app-counter-ds-cv5wc
Namespace:        go-app-counter
Priority:         0
Service Account:  bpfman-app-go-app-counter
Node:             bpfman-deployment-control-plane/172.18.0.2
Start Time:       Mon, 01 Jul 2024 15:06:11 -0400
Labels:           controller-revision-hash=6c8785d589
name=go-app-counter
pod-template-generation=1
Annotations:      <none>
Status:           Running
IP:               10.244.0.6
IPs:
IP:           10.244.0.6
Controlled By:  DaemonSet/go-app-counter-ds
Containers:
go-app-counter:
Container ID:   containerd://b9a608b9d05e98ba47b99dad50ed201422ea81ba79a4bb5e05 …
```

rename application counter bin/ds/namespace to app

---

.github/workflows/image-build.yaml

Before this was always building/pushing the dispatcher image tags regardless of the branch. This change makes sure we only update the main tags when building from main.

only push dispatcher tag when building from main

---

bpfman/src/multiprog/mod.rs
bpfman/src/multiprog/xdp.rs
docs/developer-guide/configuration.md
scripts/bpfman.toml

Based on the Ingress Node Firewall integration with bpfman, if was found that the XDP Mode handling was not ideal. For context, the valid values are HW, DRV and SKB. HW is really only applicable for Netronome hardware.
Adding the following changes:
* The config file examples (bpfman.toml) for xdp_mode were invalid. Needed an `s` on interface.eth0.
* If config file value for a given interface is not entered, SKB was the default. Changing it to DRV and and retrying as SKB if DRV or HW fail.

bpfman: XDP Mode Updates

---

bpfman/src/bin/cli/image.rs

Pr #1197 bumped the version level for object, which introduced an incompatibility between object::Endianness and aya::Endianness and caused a compile error.

Use aya::Endianness in image.rs instead of object::Endianness

---

Containerfile.bpfman
Containerfile.bpfman.local
examples/go-app-counter/container-deployment/Containerfile.go-app-counter
examples/go-kprobe-counter/container-deployment/Containerfile.go-kprobe-counter
examples/go-target/container-deployment/Containerfile.go-target
examples/go-tc-counter/container-deployment/Containerfile.go-tc-counter
examples/go-tracepoint-counter/container-deployment/Containerfile.go-tracepoint-counter
examples/go-uprobe-counter/container-deployment/Containerfile.go-uprobe-counter
examples/go-uretprobe-counter/container-deployment/Containerfile.go-uretprobe-counter
examples/go-xdp-counter/container-deployment/Containerfile.go-xdp-counter

This change addresses the FromAsCasing warnings issued by Docker during the build process by ensuring that 'as' is converted to 'AS' in the FROM directives.
Warnings observed:
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 5)
Reference: https://docs.docker.com/reference/build-checks/from-as-casing/

Fix FromAsCasing warnings in container files

---

.github/workflows/image-build.yaml
RELEASE.md
bpfman/src/lib.rs
bpfman/src/multiprog/tc.rs
bpfman/src/multiprog/xdp.rs

When a release is created, XDP and TC code should use the dispatcher from image based on a release tag, not a latest (today they always point to "quay.io/bpfman/xdp-dispatcher:v2" and "quay.io/bpfman/tc-dispatcher:v1" which are essentially "latest"). Move both image strings to a common location for easier updating and update the release doc to indication they should be updated.
Also deprecated "quay.io/bpfman/xdp-dispatcher:v1". Left the source file in place, but no longer build it automatically. Also deprecated the tags v1 and v2 in quay and now just use latest.

bpfman: dispatcher should point to release tag

---

bpfman/src/errors.rs
bpfman/src/multiprog/mod.rs
bpfman/src/multiprog/tc.rs
bpfman/src/multiprog/xdp.rs
xtask/public-api/bpfman.txt

If the TC or XDP dispatcher fails to load, subsequent load commands fail with a panic in bpfman. To fix, removed an unwrap(), add a dispatcher delete in the Dispatcher.new() function when an error occurs, and mapped some errors to new BpfmanError for dispatcher failures instead of just returning lower level error.
Resolves: #1221

bpfman: Failed dispatcher load corrupts DB

---

bpfman/src/bin/cli/get.rs

Using bpfman CLI, trying to use `bpfman get` on a program not loaded by bpfman fails.
```
$ sudo bpfman list --all
Program ID  Name             Type           Load Time
2           hid_tail_call    tracing        2024-01-03T10:38:37-0500
470         dump_bpf_map     tracing        2024-01-03T14:32:18-0500
471         dump_bpf_prog    tracing        2024-01-03T14:32:18-0500
28184                        cgroup_device  2024-02-02T10:51:40-0500
:
$ sudo bpfman get 28184
Error: get error: Database entry name does not exist in tree "28184"
```

bpfman-cli: bpfman get of non-bpfman loaded prog fails

---

.github/workflows/build.yml
bpfman/src/lib.rs
bpfman/src/types.rs

This pull request documents several functions in the bpfman crate, with examples marked with `rust,no_run` to ensure proper compilation without execution.
Fixes: https://github.com/bpfman/bpfman/issues/1050
- **Compile-Time Checks**: By using `rust,no_run`, the examples are still compiled when running `cargo test --doc`. This ensures that the code snippets are syntactically correct and that any changes to the API will be caught at compile time.
- **Avoiding Runtime Dependencies**: The examples often require a running instance of `bpfman` and specific system conditions (e.g., loaded eBPF programs). These conditions are not guaranteed in a typical documentation test environment. Using `rust,no_run` prevents these examples from failing due to unmet runtime dependencies.
- **Safety and …

bpfman/lib: add function documentation

---

bpfman/src/config.rs
bpfman/src/lib.rs
bpfman/src/oci_utils/image_manager.rs
bpfman/src/utils.rs
docs/developer-guide/configuration.md
scripts/bpfman.toml

This pr adds an option to the `Config.signing`  called `verify_enabled` that
controls whether bpfman checks the signatures on images.
`verify_enabled` is currently defaulted to `false`, due to the current issue
with TUF (https://github.com/bpfman/bpfman/issues/1241).  It should be defaulted to 
`true` after the issue is resolved.
Reading the config and setting defaults is cleaned up as well.
Fixes: https://github.com/bpfman/bpfman/issues/1239

bpfman: Make whether to use cosign configurable

---

.github/workflows/build.yml
xtask/src/public_api.rs

The public-api (cargo xtask public-api) is failing with the latest rust nightly package. Temporarily pin nightly to last known working version until source of the issue can be resolved.

ci: pin rust to nightly-2024-09-09 until public-api fixed

---

.github/workflows/image-build.yaml

Currently, image-build.yaml, which is used to build and push all bpfman related container images to quay.io, is run when PR is merged or a PR is updated and image-build.yaml file itself is modified. A new rule needs to be added such that image-build.yaml is run when a PR is updated and one of the Containerfile files is modified.

ci: run image-build.yaml when Containerfiles are updated

---

Cargo.lock
Cargo.toml
bpfman/src/config.rs
bpfman/src/oci_utils/cosign.rs
xtask/public-api/bpfman.txt

Re-enable cosign signature validation by default.
The sigstore update also included some API changes which required changes in bpfman.
Fixes: #1241

Update to sigstore v0.10.0 to pickup cosign fix

---

.github/workflows/build.yml
xtask/src/public_api.rs

Due to clippy issue, pin rust to nightly-2024-09-24.
See Issue: #1282

ci: pin to rust nightly-2024-09-24

---

README.md

The previous change didn't render right.  All the other badges have a link, but the build status doesn't.

Restore the build badge

---

.github/workflows/scorecard.yml

Add `workflow_dispatch` to the scorecard workflow so it can be manually triggered as needed while we try to improve the score.

Allow the scorecard workflow to be manually triggered

---

Cargo.lock
Cargo.toml
bpf-metrics-exporter/src/main.rs
bpfman/src/multiprog/tc.rs
bpfman/src/types.rs
xtask/public-api/bpfman.txt

Changes include:
- Update bpfman TC code to new Aya APIs
- The new Aya release now returns Aya enums for ProgramType and MapType
instead of u32. Added code to convert these enums back to u32 values 
to reduce change in the bpfman code.
- Added an enum for the new Netfilter program type introduced in Aya.

Upgrade to aya version 0.13.0 and aya-obj version 0.2.0

---

.github/workflows/build.yml
.github/workflows/rust-clippy.yaml

There's support for clippy -> sarif and therefore integration into the GitHub Code Scanning infrastructure. Let's try this out.

ci: Move clippy to a code scanning action

---

.github/workflows/image-build.yml

bpfman images are built in github actions. The binary is built using .github/wokflows/image-build.yml which is currently using ubuntu:latest. Then the image is build by copoying the binary into a container. The base image for the container is redhat/ubi9-minimal, which used glibc 2.34. Recently, ubuntu:latest change from ubuntu 22.04 (glibc 2.34) to ubuntu 24.04 (glibc 2.39). So now bpfman won't run in a redhat/ubi9-minimal base image.
This PR moves the build image back to ubuntu 22.04 (glibc 2.34). A follow-up PR #1253 will change how this works and use the same build and base images.

ci: bpfman image build needs same build and base image

---

.github/workflows/image-build.yml

bpfman images are built in github actions. The binary is built using .github/wokflows/image-build.yml which is currently using ubuntu:latest. Then the image is build by copoying the binary into a container. The base image for the container is redhat/ubi9-minimal, which used glibc 2.34. Recently, ubuntu:latest change from ubuntu 22.04 (glibc 2.34) to ubuntu 24.04 (glibc 2.39). So now bpfman won't run in a redhat/ubi9-minimal base image.
This PR moves the build image back to ubuntu 22.04 (glibc 2.34). A follow-up PR #1253 will change how this works and use the same build and base images.

image: bpfman image build needs same build and base image

---

bpfman.spec

This commit removes the executable bit from the vendored lib.rs in the
bpfman specfile as it messes up with the brp-mangle-shebangs script, which is
being run on executable files.
Resolves https://github.com/bpfman/bpfman/issues/1303

Remove executable bit from vendored lib.rs

---

docs/quick-start.md

The docs do not reference OpenShift anywhere, but specifically, the QuickStart guide. Add a note to warn potential users that OpenShift requires OperatorHub to install properly.

docs: add OpenShift note to QuickStart guide

---

.github/workflows/image-build.yml
docs/developer-guide/image-build.md

Commit e2816aae46f0536c9145ec17f37d019ae7af1eca renamed `.github/workflows/image-build.yaml` to be `.github/workflows/image-build.yml`. This PR adjusts sources to changes.

correct file extension for CI workflow configuration

---

.github/workflows/build.yml
.github/workflows/docs-build.yml
.github/workflows/image-build.yml
.github/workflows/rust-clippy.yaml
.github/workflows/scorecard.yml
Containerfile.bpfman.multi.arch

We need kernel version 6.6 or greater to build the tcx test container images and also to run tcx integration tests.
We also have potential incompatibilies because redhat/ubi9-minimal is being used in Containerfile.bpfman.multi.arch, but ubuntu is being used to build the executables in image-build.yml.
Using Ubuntu-latest also has the potential to change versions without our knowing so we should pin down the version.
Using Ubuntu 24.04 for the bpfman image build and container can be revisited if we move to the approach in https://github.com/bpfman/bpfman/pull/1253.

Use Ubuntu 24.04 everywhere

---

.github/workflows/image-build.yml
Containerfile.bpfman.multi.arch
examples/go-app-counter/bpf/tcx_counter.h
examples/go-tcx-counter/bpf/tcx_counter.c
tests/integration-test/bpf/tcx_test.bpf.c

We're having failures in pulling/loading bpf programs with the new image.  It's not fully debugged, but this is the likely change.

Move bpfman container back to redhat/ubi9-minimal

---

.github/workflows/image-build.yml
Containerfile.bpfman.local
Containerfile.bpfman.multi.arch
bpfman/src/lib.rs
examples/go-app-counter/bpf/tcx_counter.h
examples/go-tcx-counter/bpf/tcx_counter.c
tests/integration-test/bpf/tcx_test.bpf.c

Backout #1325, which moved image building from Ubuntu 24.04 (which is needed for TCX) to ubi9-minimal. #1325 was needed because images originally built with Ubuntu 24.04 were failing to load eBPF programs because of Cosign failures. Turns out that those failures were due to ca-certicates not being installed in Ubunut 24.04 base images. So this PR also adds ca-certicates to the bpfman base image.
To allow local building of bpfman images that are consistent with github built images, this PR also moves Containerfile.bpfman.local to build with Ubuntu 24.04.

image: Move bpfman container back to Ubuntu 24.04

---

tests/integration-test/bpf/kprobe_globals.bpf.c

As an example, this program can be installed with the following bpfman cli command:
bpfman load image \
-g sampling=01020304 trace_messages=05 enable_rtt=06 enable_pca=07 enable_dns_tracking=08 enable_flows_filtering=09 \ dns_port=0A0B enable_network_events_monitoring=0C network_events_monitoring_groupid=0D \ --image-url quay.io/bpfman-bytecode/kprobe_globals:latest \ -n kprobe_globals kprobe --fn-name try_to_wake_up

Add an eBPF program with 9 global variables

---

bpfman/src/bin/cli/args.rs
docs/getting-started/cli-guide.md
docs/getting-started/example-bpf-local.md
docs/getting-started/example-bpf.md
examples/pkg/config-mgmt/param.go
tests/integration-test/src/tests/utils.rs

The documentation on examples has a section on building the examples which was still using the `docker build --build-arg ...` style. Switch it to use the `bpfman build image` command.
Also found a few spots in the documents that were still referencing the old object names, like `bpf_bpfel.o`. With multi-arch, all our bytecode object files have the arch in the name, like `bpf_x86_bpfel.o`.

doc: update example building to use bpfman image build

---

bpfman/src/lib.rs
bpfman/src/multiprog/mod.rs
bpfman/src/multiprog/tc.rs
bpfman/src/multiprog/xdp.rs
bpfman/src/types.rs
bpfman/src/utils.rs
tests/integration-test/src/tests/e2e.rs
xtask/public-api/bpfman.txt

This fix saves the network namespace ID when the program is loaded so it can be retrieved later when the program is being deleted even if the network namespace is deleted first.
Fixes: #1362

Fix Error deleting tc and xdp programs after netns deleted

---

README.md
docs/blog/posts/ebpf-container-challenges.md
docs/design/clusterVsNamespaceScoped.md
docs/developer-guide/develop-operator.md
docs/getting-started/building-bpfman.md
docs/getting-started/example-bpf-k8s.md
docs/getting-started/operator-quick-start.md
docs/getting-started/overview.md
docs/getting-started/running-release.md
docs/index.md
mkdocs.yml

Add a design document for Cluster vs Namespace Scoped CRDs in bpfman as well as update the bpfman documentation to include Namespace Scoped CRDs.

doc: add design document for Cluster vs Namespace

---

.github/workflows/build.yml

Revert softprops/action-gh-release from v2.2.0 to v2.1.0 due to "Error: Request body length does not match content-length header"
See: https://github.com/softprops/action-gh-release/issues/556

revert softprops/action-gh-release

---

bpfman/src/bin/cli/args.rs

fix that arm64 bytecode file was recognized as an arm arch when using `bpfman image generate-build-args --cilium-ebpf-project <project>`

cli: fix arm64 arch recongnization with --cilium-ebpf-project flag

---

bpf-log-exporter/src/main.rs
bpfman/src/lib.rs
bpfman/src/oci_utils/image_manager.rs
bpfman/src/oci_utils/mod.rs
bpfman/src/utils.rs
tests/integration-test/src/tests/e2e.rs
xtask/public-api/bpfman.txt

Image pull was failing with:
```
$ sudo bpfman load image --image-url quay.io/netobserv/ebpf-bytecode:e705638 \
--name tcx_ingress_flow_parse tcx --iface eno3 --priority 100 --direction ingress
Error: failed to read db: Database entry quay.io_netobserv_ebpf-bytecode_mainc45136dba8fb3c73b87df1a0b125b5b354ae026cdd0ce2740dcf48c3ad54da10 does not exist in tree "__sled__default":
```
After further investigation, it was discovered that if bpfman is uninstalled and loaded fresh (empty database), the following error occurs:
```
$ sudo bpfman load image --image-url quay.io/netobserv/ebpf-bytecode:e705638 \
--name tcx_ingress_flow_parse tcx --iface eno3 --priority 100 --direction ingress
Error: expected `,` or `}` at line 5 column 1
```
After adding additional debug logs, the primary issue was that …

image pull failure

---

.github/workflows/build.yml
.github/workflows/docs-build.yml
requirements.txt

In github actions for building the docs, while installing the dependancies from requirements.txt, lxml started failing. The first failure was:
```
pkg_resources.html
Building lxml version 4.9.3.
Building without Cython.
Error: Please make sure the libxml2 and libxslt development packages are installed.
```
Once libxml2 and libxslt were installed using `apt-get install`, lxml failed with lots of compile errors. Bumping the versionfrom 4.9.3 to 5.0.2 fixed the compile errors.

docs: github doc build fails in package lxml

---

.github/workflows/docs-build.yml

When a PR merges, a job from docs-build.yml is run. This is currently failing with:
```
pip install -r requirements.txt
shell: /usr/bin/bash -e {0}
:
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
2to3 python-is-python3
E: Package 'python' has no installation candidate
E: Unable to locate package install
Error: Process completed with exit code 100.
```

docs: building docs after a PR merges fails

---

.github/workflows/scorecard.yml

Fixes #1358 
The scorecard workflow referenced
`upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08` with a
misleading comment (`# v3.pre.node20`). This SHA corresponds to
`v4.6.0`, as confirmed by checking the tags in the upstream
repository:
% repoduper https://github.com/actions/upload-artifact.git
% cd upload-artifact
% pwd
/home/aim/src/github.com/actions/upload-artifact
% git tag --contains 65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
v4
v4.6.0
Update the comment to `# @v4` to match other workflows and reflect the
correct version.
Signed-off-by: Andrew McDermott <amcdermo@redhat.com>

ci: update scorecard workflow to clarify upload-artifact version

---

bpfman/src/config.rs

The last signing event from sigstore/root-signing included a change that broke sigstore-rs. bpfman cannot load any images at the moment. Change the interanl default for `verify_enabled` to false until sigstore fixes their issue.
Related: #1399

disable image verification until sigstore fixed

---

Cargo.lock
Cargo.toml
bpfman-api/Cargo.toml
bpfman/src/bin/cli/args.rs
bpfman/src/config.rs
bpfman/src/lib.rs
bpfman/src/oci_utils/cosign.rs
bpfman/src/types.rs
tests/integration-test/src/tests/basic.rs
xtask/src/public_api.rs

sigstore/root-signing had a new sigining event that fixed the previous issue. Update to new version of sigstore (0.11.0) and turn image verification back on by default.
Also changed the error message returned to the user.
Original:
```
$ sudo bpfman load file --path bpfman/examples/go-xdp-counter/bpf_x86_bpfel.o --name "xdp_stats" xdp --iface eno3 --priority 35
Error: An error occurred. Unable to initialize ImageManager: Error spawning blocking task to build sigstore repo inside of tokio: Failed to parse root metadata: Invalid key ID 7247f0dbad85b147e1863bade761243cc785dcb7aa410e7105dd3d2b61a36d2c: calculated 0c87432c3bf09fd99189fdc32fa5eaedf4e4a5fac7bab73fa04a2e0fc64af6f5 at line 76 column 4
```
New:
```
$ sudo bpfman load file --path bpfman/examples/go-xdp-counter/bpf_x86_bpfel.o --name …
```

reenable image verification

---

bpfman/src/lib.rs
bpfman/src/multiprog/mod.rs
bpfman/src/multiprog/tc.rs

For TC Programs:
When a TC program is attached within a network namespace, switch to that namespace to detach the TC dispatcher after removing the last program.
For TC and XDP Programs:
If TC or XDP programs are attached within a network namespace, avoid attempting to rebuild and reattach the dispatcher if the namespace has already been deleted when the programs are removed.
Fixes: #1402

Fix errors deleting tc and xdp programs in network namespaces

---

bpfman.spec

Upstream RPM builds are failing:
```
error: failed to run custom build command for `aws-lc-sys v0.25.1`
:
--- stderr
thread 'main' panicked at /builddir/build/BUILD/bpfman-897329fbe2222b97998ac5a13f24b3e1b37d6247/vendor/bindgen/lib.rs:622:31:
Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
```

rpm: RPM builds failing - clang

---

examples/config/base/go-xdp-counter/deployment.yaml

A temporary change to the go-xdp-counter deployment was made to launch the example in the bpfman namespace to test security-profiles-operator logic and the temporary change got accidentally pushed and merged with #1388. Revert those changes.

revert go-xdp-counter change

---

Cargo.lock
Cargo.toml
bpf-log-exporter/Cargo.toml
bpfman-api/Cargo.toml
bpfman-api/src/bin/rpc/rpc.rs
bpfman-api/src/bin/rpc/storage.rs
bpfman/Cargo.toml
bpfman/src/bin/cli/get.rs
bpfman/src/bin/cli/image.rs
bpfman/src/bin/cli/list.rs
bpfman/src/bin/cli/load.rs
bpfman/src/bin/cli/main.rs
bpfman/src/bin/cli/unload.rs
bpfman/src/lib.rs
bpfman/src/multiprog/mod.rs
bpfman/src/multiprog/tc.rs
bpfman/src/multiprog/xdp.rs
bpfman/src/netlink.rs
bpfman/src/oci_utils/cosign.rs
bpfman/src/oci_utils/image_manager.rs
bpfman/src/oci_utils/mod.rs
bpfman/src/static_program.rs
bpfman/src/types.rs

When we moved bpfman to be a oneshot commandline program instead of being a daemon we noted that we should run sync and not async given that a lot of the work we do is synchronous.
The blocking factor here was that sigstore and oci_distribution required us to use tokio.
This solve this, we introduce a new wrapper called BlockingWrapper that lets us run:
- Async code from a sync context (i.e oci_utils from bpfman)
- Async code from a sync context from an async context (i.e bpfman-rpc -> bpfman -> oci_utils)
In effect, bpfman can remain sync, while using dependnecies that might require an async runtime like tokio.

chore: Unasync all the things

---

docs/getting-started/running-release.md
docs/quick-start.md

This PR fixes the old manifests links to install the crds and operator for `bpfman`

fix: correct links to install the crds and operator

---

Cargo.lock
Cargo.toml
Containerfile.bpfman.local
bpfman-api/Cargo.toml
bpfman-api/src/bin/rpc/main.rs
bpfman-api/src/bin/rpc/rpc.rs
bpfman-api/src/bin/rpc/serve.rs
bpfman-api/src/bin/rpc/storage.rs
bpfman/Cargo.toml
bpfman/src/oci_utils/cosign.rs
bpfman/src/oci_utils/image_manager.rs
bpfman/src/oci_utils/mod.rs

@Billy99 reported that bpfman-rpc was performing poorly since the changes to use only sync code inside bpfman.
There were 2 reasons for this:
1. There's a possibility that the CSI code and the RPC code can both acquire the database lock at the same time. The lock is now protected with a Mutex to ensure this can't happen
2. Within the BlockingWrapper, calling `block_on` with the future performed poorly. Instead, we spawn the future on the runtime and then await it within the block_on
With these changes, bpfman-rpc performance is back where it should be. In debugging this I also noticed that error logs don't propagate to the bpfman-rpc logs in Kubernetes. I've adjusted the code there to ensure that errors are appropriately logged before being returned to the RPC client.

fix(bpfman-rpc): bpfman-rpc performance issues

---

examples/config/base/go-app-counter/bytecode.yaml
examples/config/base/go-kprobe-counter/bytecode.yaml
examples/config/base/go-tcx-counter/bytecode.yaml
examples/config/base/go-tracepoint-counter/bytecode.yaml
examples/config/base/go-uprobe-counter/bytecode.yaml
examples/config/base/go-uretprobe-counter/bytecode.yaml
examples/config/base/go-xdp-counter/bytecode.yaml

Update all the bytecode.yaml files in the examples directory, which are responsible for loading the bytecode, to use the new ClusterBpfApplication CRDs instead of the *Program CRDs which have been removed.

Update examples to use new ClusterBpfApplication

---

.pre-commit-config.yaml
docs/developer-guide/pre-commit-hook.md
mkdocs.yml

This PR adds pre-commit hooks for both yamllint and clippy.
Resolves https://github.com/bpfman/bpfman/issues/1297

Add pre-commit hook

---

examples/config/base/go-app-counter/bytecode.yaml
examples/config/base/go-kprobe-counter/bytecode.yaml
examples/config/base/go-tc-counter/bytecode.yaml
examples/config/base/go-tcx-counter/bytecode.yaml
examples/config/base/go-tracepoint-counter/bytecode.yaml
examples/config/base/go-uprobe-counter/bytecode.yaml
examples/config/base/go-uretprobe-counter/bytecode.yaml
examples/config/base/go-xdp-counter/bytecode.yaml

required based on https://github.com/bpfman/bpfman-operator/pull/413 new apis changes
UT
- `make deploy-app`
```sh
oc get clusterbpfapplication
NAME          NODESELECTOR   STATUS    AGE
app-counter                  Success   51s
```
- `make deploy-kprobe`
```sh
oc get clusterbpfapplication
NAME                        NODESELECTOR   STATUS    AGE
go-kprobe-counter-example                  Success   17s
```
- `make deploy-tcx`
```sh
oc get clusterbpfapplication
NAME                     NODESELECTOR   STATUS    AGE
go-tcx-counter-example                  Success   20s
```
- `make deploy-tracepoint`
```sh
oc get clusterbpfapplication
NAME                            NODESELECTOR   STATUS    AGE
go-tracepoint-counter-example                  Success   25s
```
- `make deploy-xdp`
```sh
oc get …
```

update examples based on recent APIs review changes

---

Cargo.lock
Cargo.toml
Containerfile.bpfman.local
Cross.toml
bpfman-api/Cargo.toml
bpfman.spec

See: https://aws.github.io/aws-lc-rs/requirements/linux.html
We can install bindgen-cli on any target that requires it. This avoid having to manage a direct dependency on aws-lc-rs.

chore: Remove aws-lc-rs dependency

---

Containerfile.bpfman.local
bpfman/src/lib.rs

This closes #1451 
Two changes:
- `Containerfile.bpfman.local`: copy binaries to `/usr/local/sbin/` instead of `/`. This means the binaries are always found, regardless of changes to the current `WORKDIR`.
- The entrypoint was updated accordingly.
- For some reason, the build was failing for me unless I also installed `cmake` and `clang` so I went ahead and added those two packages to the last `apt-get install` command.
- `bpfman/src/lib.rs`: print out one additional message when the `bpfman-ns` binary is not found.

fix: add binaries to container PATH

---

bpfman-api/src/bin/rpc/main.rs
bpfman-api/src/bin/rpc/rpc.rs
bpfman/src/bin/cli/args.rs
bpfman/src/bin/cli/attach.rs
bpfman/src/bin/cli/get.rs
bpfman/src/bin/cli/list.rs
bpfman/src/bin/cli/load.rs
bpfman/src/bin/cli/main.rs
bpfman/src/bin/cli/table.rs
bpfman/src/lib.rs
bpfman/src/types.rs
scripts/nsadd.sh

Add to the CLI the ability to get and list link data. This requires adding `program` and `link` subcommands to the `bpfman get` and `bpfman list` commands.
Resolves: #1415 
Resolves: #1426

cli: add get and list link

---

.pre-commit-config.yaml

Solves issue #1489 
This PR adds golangci-lint to our pre-commit hooks configuration, ensuring that Go code is linted locally before being committed.
- Added golangci-lint hook using the same version (v1.54.2) as our CI workflow
- Configured to run on all Go files in the project
- Set pass_filenames: false to ensure the linter examines the entire codebase
To test these changes locally:
1. Install pre-commit: `pip install pre-commit`
2. Install golangci-lint
3. Run `pre-commit install` in your local repository
4. Test with `pre-commit run golangci-lint`

Added golangci-lint to the pre-commit hooks

---

.vscode/settings.json

Solves Issue: #1475
Correct the path for the YAML schema in the VSCode settings to ensure proper validation of the GitHub workflow file.

Update YAML schema path in VSCode settings

---

docs/developer-guide/logging.md
docs/developer-guide/xdp-overview.md
docs/getting-started/building-bpfman.md
docs/getting-started/cli-guide.md
docs/getting-started/example-bpf-local.md
docs/getting-started/launching-bpfman.md
docs/getting-started/running-release.md
docs/getting-started/running-rpm.md
docs/getting-started/troubleshooting.md
docs/quick-start.md

Update the CLI portion of the documents to match the changes that were made as part of the load/attach split and adding `program` and `link` to the `bpfman list` and `bpfman get` commands.

docs: update docs to match the load/attach changes

---

Cargo.lock
Cargo.toml
bpf-metrics-exporter/Cargo.toml
bpf-metrics-exporter/build.rs
bpf-metrics-exporter/src/main.rs
bpfman-api/Cargo.toml
bpfman-api/build.rs
bpfman-api/src/bin/rpc/main.rs
bpfman-ns/Cargo.toml
bpfman-ns/build.rs
bpfman-ns/src/main.rs
bpfman/Cargo.toml
bpfman/build.rs
bpfman/src/bin/cli/args.rs
buildinfo/Cargo.toml
buildinfo/src/lib.rs

Fixes https://github.com/bpfman/bpfman/issues/1398.
This PR introduces standardised version information to all of bpfman’s CLI binaries (except bpf-log-exporter, which has no prior argument parsing), making the --version and -V flags available for all top-level commands. 
All CLI tools now embed standardised version metadata using a shared buildinfo crate and a single API (generate_version_info()) called from each binary’s build script. The version string includes the package version (from Cargo.toml), the Git commit hash (with a dirty-state indicator if the working tree is not clean), the build timestamp (overridable via environment variable for CI), the Rust compiler version, and the Git repository origin URL (from the origin remote). 
The version strings provide valuable context for …

feat: Add version information to CLI tools

---

examples/config/base/go-xdp-counter-sharing-map/bytecode.yaml

When running `make -C examples deploy`, the go-xdp-counter-sharing-map example was failing with an error due to incorrect field names in the ClusterBpfApplication resource definition.
The issue was that the program type was specified as "xdp" (lowercase) instead of "XDP" (uppercase), and the XDP configuration was incorrectly nested under "xdpInfo" instead of "xdp".
This change fixes the field names to match the expected ClusterBpfApplication schema, allowing the example to deploy successfully alongside the other examples.

Fix go-xdp-counter-sharing-map example deployment error

---

docs/developer-guide/develop-operator.md

This adds a note to the documentation that explains that SPO is required to be installed manually when installing via OLM on OpenShift.
Before submitting a Pull Request, please ensure you've done the following:
- 📖 Read the Bpfman Contributing Guide: https://github.com/bpfman/bpfman/blob/main/CONTRIBUTING.md
- 📖 Read the Bpfman Code of Conduct: https://github.com/bpfman/bpfman/blob/main/CODE_OF_CONDUCT.md
- ✅ Add tests according to our Test Policy: https://github.com/bpfman/bpfman/blob/main/CONTRIBUTING.md#test-policy
- 📝 Use descriptive commit messages: https://cbea.ms/git-commit/
- 📗 Update any related documentation.
_We strongly encourage you to add a test for your changes._
have not been included_
```sh
cd bpfman/
cargo +nightly clippy --all -- --deny warnings
```
```sh
cargo +nightly …
```

docs: Add note on Security Profiles Operator

---

bpfman/src/multiprog/tc.rs
bpfman/src/multiprog/xdp.rs

Add information about the map's location if loading it fails.
Having this logging helped me better understand the mechanics of https://github.com/bpfman/bpfman/pull/1577
Before submitting a Pull Request, please ensure you've done the following:
- 📖 Read the Bpfman Contributing Guide: https://github.com/bpfman/bpfman/blob/main/CONTRIBUTING.md
- 📖 Read the Bpfman Code of Conduct: https://github.com/bpfman/bpfman/blob/main/CODE_OF_CONDUCT.md
- ✅ Add tests according to our Test Policy: https://github.com/bpfman/bpfman/blob/main/CONTRIBUTING.md#test-policy
- 📝 Use descriptive commit messages: https://cbea.ms/git-commit/
- 📗 Update any related documentation.
_We strongly encourage you to add a test for your changes._
have not been included_
```sh
cd bpfman/
cargo +nightly clippy --all -- --deny …
```

Improve error display for loading pinned BPF maps

---

bpfman/src/lib.rs
bpfman/src/utils.rs

Before submitting a Pull Request, please ensure you've done the following:
- 📖 Read the Bpfman Contributing Guide: https://github.com/bpfman/bpfman/blob/main/CONTRIBUTING.md
- 📖 Read the Bpfman Code of Conduct: https://github.com/bpfman/bpfman/blob/main/CODE_OF_CONDUCT.md
- ✅ Add tests according to our Test Policy: https://github.com/bpfman/bpfman/blob/main/CONTRIBUTING.md#test-policy
- 📝 Use descriptive commit messages: https://cbea.ms/git-commit/
- 📗 Update any related documentation.
* Improved error handling in case loading a pinned map fails.
* Moved DB from /var/lib/bpfman/db to /run/bpfman/db
Closes: #1563
_We strongly encourage you to add a test for your changes._
have not been included_
```sh
cd bpfman/
cargo +nightly clippy --all -- --deny warnings
```
> I had to run: ` cargo …

Fix: After a server reboot the state is corrupted
